-- | ************************************************************ |
-- | * Glass Walls & Secret Doors by LordYig
-- | * Version : 1.0
-- | ************************************************************ |
-- Secret Doors Definition
-- Dungeon Doors
defineObject{
	name = "dungeon_glass_secret_door_green_01",
	class = "Door",
	model = "mod_assets/models/env/secret_doors/dungeon_glass_secret_door_green_01.fbx",
	openSound = "wall_sliding",
	closeSound = "wall_sliding",
	lockSound = "wall_sliding_lock",
	openVelocity = 0.5,
	closeVelocity = -0.5,
	secretDoor = true,
	placement = "wall",
	editorIcon = 120,
}
defineObject{
	name = "dungeon_glass_secret_door_green_02",
	class = "Door",
	model = "mod_assets/models/env/secret_doors/dungeon_glass_secret_door_green_02.fbx",
	openSound = "wall_sliding",
	closeSound = "wall_sliding",
	lockSound = "wall_sliding_lock",
	openVelocity = 0.5,
	closeVelocity = -0.5,
	secretDoor = true,
	placement = "wall",
	editorIcon = 120,
}
defineObject{
	name = "dungeon_glass_secret_door_green_03",
	class = "Door",
	model = "mod_assets/models/env/secret_doors/dungeon_glass_secret_door_green_03.fbx",
	openSound = "wall_sliding",
	closeSound = "wall_sliding",
	lockSound = "wall_sliding_lock",
	openVelocity = 0.5,
	closeVelocity = -0.5,
	secretDoor = true,
	placement = "wall",
	editorIcon = 120,
}
defineObject{
	name = "dungeon_glass_secret_door_green_04",
	class = "Door",
	model = "mod_assets/models/env/secret_doors/dungeon_glass_secret_door_green_04.fbx",
	openSound = "wall_sliding",
	closeSound = "wall_sliding",
	lockSound = "wall_sliding_lock",
	openVelocity = 0.5,
	closeVelocity = -0.5,
	secretDoor = true,
	placement = "wall",
	editorIcon = 120,
}
defineObject{
	name = "dungeon_glass_secret_door_green_05",
	class = "Door",
	model = "mod_assets/models/env/secret_doors/dungeon_glass_secret_door_green_05.fbx",
	openSound = "wall_sliding",
	closeSound = "wall_sliding",
	lockSound = "wall_sliding_lock",
	openVelocity = 0.5,
	closeVelocity = -0.5,
	secretDoor = true,
	placement = "wall",
	editorIcon = 120,
}
defineObject{
	name = "dungeon_glass_secret_door_green_06",
	class = "Door",
	model = "mod_assets/models/env/secret_doors/dungeon_glass_secret_door_green_06.fbx",
	openSound = "wall_sliding",
	closeSound = "wall_sliding",
	lockSound = "wall_sliding_lock",
	openVelocity = 0.5,
	closeVelocity = -0.5,
	secretDoor = true,
	placement = "wall",
	editorIcon = 120,
}
defineObject{
	name = "dungeon_glass_secret_door_green_07",
	class = "Door",
	model = "mod_assets/models/env/secret_doors/dungeon_glass_secret_door_green_07.fbx",
	openSound = "wall_sliding",
	closeSound = "wall_sliding",
	lockSound = "wall_sliding_lock",
	openVelocity = 0.5,
	closeVelocity = -0.5,
	secretDoor = true,
	placement = "wall",
	editorIcon = 120,
}
defineObject{
	name = "dungeon_glass_secret_door_green_08",
	class = "Door",
	model = "mod_assets/models/env/secret_doors/dungeon_glass_secret_door_green_08.fbx",
	openSound = "wall_sliding",
	closeSound = "wall_sliding",
	lockSound = "wall_sliding_lock",
	openVelocity = 0.5,
	closeVelocity = -0.5,
	secretDoor = true,
	placement = "wall",
	editorIcon = 120,
}
defineObject{
	name = "dungeon_glass_secret_door_yellow_01",
	class = "Door",
	model = "mod_assets/models/env/secret_doors/dungeon_glass_secret_door_yellow_01.fbx",
	openSound = "wall_sliding",
	closeSound = "wall_sliding",
	lockSound = "wall_sliding_lock",
	openVelocity = 0.5,
	closeVelocity = -0.5,
	secretDoor = true,
	placement = "wall",
	editorIcon = 120,
}
defineObject{
	name = "dungeon_glass_secret_door_yellow_02",
	class = "Door",
	model = "mod_assets/models/env/secret_doors/dungeon_glass_secret_door_yellow_02.fbx",
	openSound = "wall_sliding",
	closeSound = "wall_sliding",
	lockSound = "wall_sliding_lock",
	openVelocity = 0.5,
	closeVelocity = -0.5,
	secretDoor = true,
	placement = "wall",
	editorIcon = 120,
}
defineObject{
	name = "dungeon_glass_secret_door_yellow_03",
	class = "Door",
	model = "mod_assets/models/env/secret_doors/dungeon_glass_secret_door_yellow_03.fbx",
	openSound = "wall_sliding",
	closeSound = "wall_sliding",
	lockSound = "wall_sliding_lock",
	openVelocity = 0.5,
	closeVelocity = -0.5,
	secretDoor = true,
	placement = "wall",
	editorIcon = 120,
}
defineObject{
	name = "dungeon_glass_secret_door_yellow_04",
	class = "Door",
	model = "mod_assets/models/env/secret_doors/dungeon_glass_secret_door_yellow_04.fbx",
	openSound = "wall_sliding",
	closeSound = "wall_sliding",
	lockSound = "wall_sliding_lock",
	openVelocity = 0.5,
	closeVelocity = -0.5,
	secretDoor = true,
	placement = "wall",
	editorIcon = 120,
}
defineObject{
	name = "dungeon_glass_secret_door_yellow_05",
	class = "Door",
	model = "mod_assets/models/env/secret_doors/dungeon_glass_secret_door_yellow_05.fbx",
	openSound = "wall_sliding",
	closeSound = "wall_sliding",
	lockSound = "wall_sliding_lock",
	openVelocity = 0.5,
	closeVelocity = -0.5,
	secretDoor = true,
	placement = "wall",
	editorIcon = 120,
}
defineObject{
	name = "dungeon_glass_secret_door_yellow_06",
	class = "Door",
	model = "mod_assets/models/env/secret_doors/dungeon_glass_secret_door_yellow_06.fbx",
	openSound = "wall_sliding",
	closeSound = "wall_sliding",
	lockSound = "wall_sliding_lock",
	openVelocity = 0.5,
	closeVelocity = -0.5,
	secretDoor = true,
	placement = "wall",
	editorIcon = 120,
}
defineObject{
	name = "dungeon_glass_secret_door_yellow_07",
	class = "Door",
	model = "mod_assets/models/env/secret_doors/dungeon_glass_secret_door_yellow_07.fbx",
	openSound = "wall_sliding",
	closeSound = "wall_sliding",
	lockSound = "wall_sliding_lock",
	openVelocity = 0.5,
	closeVelocity = -0.5,
	secretDoor = true,
	placement = "wall",
	editorIcon = 120,
}
defineObject{
	name = "dungeon_glass_secret_door_yellow_08",
	class = "Door",
	model = "mod_assets/models/env/secret_doors/dungeon_glass_secret_door_yellow_08.fbx",
	openSound = "wall_sliding",
	closeSound = "wall_sliding",
	lockSound = "wall_sliding_lock",
	openVelocity = 0.5,
	closeVelocity = -0.5,
	secretDoor = true,
	placement = "wall",
	editorIcon = 120,
}
-- Temple Doors
defineObject{
	name = "temple_glass_secret_door_blue_01",
	class = "Door",
	model = "mod_assets/models/env/secret_doors/temple_glass_secret_door_blue_01.fbx",
	openSound = "wall_sliding",
	closeSound = "wall_sliding",
	lockSound = "wall_sliding_lock",
	openVelocity = 0.5,
	closeVelocity = -0.5,
	secretDoor = true,
	placement = "wall",
	editorIcon = 120,
}
defineObject{
	name = "temple_glass_secret_door_blue_02",
	class = "Door",
	model = "mod_assets/models/env/secret_doors/temple_glass_secret_door_blue_02.fbx",
	openSound = "wall_sliding",
	closeSound = "wall_sliding",
	lockSound = "wall_sliding_lock",
	openVelocity = 0.5,
	closeVelocity = -0.5,
	secretDoor = true,
	placement = "wall",
	editorIcon = 120,
}
defineObject{
	name = "temple_glass_secret_door_blue_03",
	class = "Door",
	model = "mod_assets/models/env/secret_doors/temple_glass_secret_door_blue_03.fbx",
	openSound = "wall_sliding",
	closeSound = "wall_sliding",
	lockSound = "wall_sliding_lock",
	openVelocity = 0.5,
	closeVelocity = -0.5,
	secretDoor = true,
	placement = "wall",
	editorIcon = 120,
}
defineObject{
	name = "temple_glass_secret_door_blue_04",
	class = "Door",
	model = "mod_assets/models/env/secret_doors/temple_glass_secret_door_blue_04.fbx",
	openSound = "wall_sliding",
	closeSound = "wall_sliding",
	lockSound = "wall_sliding_lock",
	openVelocity = 0.5,
	closeVelocity = -0.5,
	secretDoor = true,
	placement = "wall",
	editorIcon = 120,
}
defineObject{
	name = "temple_glass_secret_door_blue_05",
	class = "Door",
	model = "mod_assets/models/env/secret_doors/temple_glass_secret_door_blue_05.fbx",
	openSound = "wall_sliding",
	closeSound = "wall_sliding",
	lockSound = "wall_sliding_lock",
	openVelocity = 0.5,
	closeVelocity = -0.5,
	secretDoor = true,
	placement = "wall",
	editorIcon = 120,
}
defineObject{
	name = "temple_glass_secret_door_blue_06",
	class = "Door",
	model = "mod_assets/models/env/secret_doors/temple_glass_secret_door_blue_06.fbx",
	openSound = "wall_sliding",
	closeSound = "wall_sliding",
	lockSound = "wall_sliding_lock",
	openVelocity = 0.5,
	closeVelocity = -0.5,
	secretDoor = true,
	placement = "wall",
	editorIcon = 120,
}
defineObject{
	name = "temple_glass_secret_door_blue_07",
	class = "Door",
	model = "mod_assets/models/env/secret_doors/temple_glass_secret_door_blue_07.fbx",
	openSound = "wall_sliding",
	closeSound = "wall_sliding",
	lockSound = "wall_sliding_lock",
	openVelocity = 0.5,
	closeVelocity = -0.5,
	secretDoor = true,
	placement = "wall",
	editorIcon = 120,
}
defineObject{
	name = "temple_glass_secret_door_blue_08",
	class = "Door",
	model = "mod_assets/models/env/secret_doors/temple_glass_secret_door_blue_08.fbx",
	openSound = "wall_sliding",
	closeSound = "wall_sliding",
	lockSound = "wall_sliding_lock",
	openVelocity = 0.5,
	closeVelocity = -0.5,
	secretDoor = true,
	placement = "wall",
	editorIcon = 120,
}
defineObject{
	name = "temple_glass_secret_door_red_01",
	class = "Door",
	model = "mod_assets/models/env/secret_doors/temple_glass_secret_door_red_01.fbx",
	openSound = "wall_sliding",
	closeSound = "wall_sliding",
	lockSound = "wall_sliding_lock",
	openVelocity = 0.5,
	closeVelocity = -0.5,
	secretDoor = true,
	placement = "wall",
	editorIcon = 120,
}
defineObject{
	name = "temple_glass_secret_door_red_02",
	class = "Door",
	model = "mod_assets/models/env/secret_doors/temple_glass_secret_door_red_02.fbx",
	openSound = "wall_sliding",
	closeSound = "wall_sliding",
	lockSound = "wall_sliding_lock",
	openVelocity = 0.5,
	closeVelocity = -0.5,
	secretDoor = true,
	placement = "wall",
	editorIcon = 120,
}
defineObject{
	name = "temple_glass_secret_door_red_03",
	class = "Door",
	model = "mod_assets/models/env/secret_doors/temple_glass_secret_door_red_03.fbx",
	openSound = "wall_sliding",
	closeSound = "wall_sliding",
	lockSound = "wall_sliding_lock",
	openVelocity = 0.5,
	closeVelocity = -0.5,
	secretDoor = true,
	placement = "wall",
	editorIcon = 120,
}
defineObject{
	name = "temple_glass_secret_door_red_04",
	class = "Door",
	model = "mod_assets/models/env/secret_doors/temple_glass_secret_door_red_04.fbx",
	openSound = "wall_sliding",
	closeSound = "wall_sliding",
	lockSound = "wall_sliding_lock",
	openVelocity = 0.5,
	closeVelocity = -0.5,
	secretDoor = true,
	placement = "wall",
	editorIcon = 120,
}
defineObject{
	name = "temple_glass_secret_door_red_05",
	class = "Door",
	model = "mod_assets/models/env/secret_doors/temple_glass_secret_door_red_05.fbx",
	openSound = "wall_sliding",
	closeSound = "wall_sliding",
	lockSound = "wall_sliding_lock",
	openVelocity = 0.5,
	closeVelocity = -0.5,
	secretDoor = true,
	placement = "wall",
	editorIcon = 120,
}
defineObject{
	name = "temple_glass_secret_door_red_06",
	class = "Door",
	model = "mod_assets/models/env/secret_doors/temple_glass_secret_door_red_06.fbx",
	openSound = "wall_sliding",
	closeSound = "wall_sliding",
	lockSound = "wall_sliding_lock",
	openVelocity = 0.5,
	closeVelocity = -0.5,
	secretDoor = true,
	placement = "wall",
	editorIcon = 120,
}
defineObject{
	name = "temple_glass_secret_door_red_07",
	class = "Door",
	model = "mod_assets/models/env/secret_doors/temple_glass_secret_door_red_07.fbx",
	openSound = "wall_sliding",
	closeSound = "wall_sliding",
	lockSound = "wall_sliding_lock",
	openVelocity = 0.5,
	closeVelocity = -0.5,
	secretDoor = true,
	placement = "wall",
	editorIcon = 120,
}
defineObject{
	name = "temple_glass_secret_door_red_08",
	class = "Door",
	model = "mod_assets/models/env/secret_doors/temple_glass_secret_door_red_08.fbx",
	openSound = "wall_sliding",
	closeSound = "wall_sliding",
	lockSound = "wall_sliding_lock",
	openVelocity = 0.5,
	closeVelocity = -0.5,
	secretDoor = true,
	placement = "wall",
	editorIcon = 120,
}