-- | ************************************************************ |
-- | * Glass Walls & Secret Doors by LordYig
-- | * Version : 1.0
-- | ************************************************************ |
-- Green Glass
defineMaterial{
	name = "glass_frame_green_01",
	diffuseMap = "mod_assets/textures/env/glass_doors/glass_frame_green_01_diff.tga",
	specularMap = "mod_assets/textures/env/glass_doors/glass_frame_01_spec.tga",
	normalMap = "mod_assets/textures/env/glass_doors/glass_frame_01_normal.tga",
	doubleSided = false,
	lighting = false,
	alphaTest = true,
	blendMode = "Translucent",
	textureAddressMode = "Wrap",
	glossiness = 1,
	depthBias = 0,
}
defineMaterial{
	name = "glass_frame_green_02",
	diffuseMap = "mod_assets/textures/env/glass_doors/glass_frame_green_02_diff.tga",
	specularMap = "mod_assets/textures/env/glass_doors/glass_frame_02_spec.tga",
	normalMap = "mod_assets/textures/env/glass_doors/glass_frame_02_normal.tga",
	doubleSided = false,
	lighting = false,
	alphaTest = true,
	blendMode = "Translucent",
	textureAddressMode = "Wrap",
	glossiness = 1,
	depthBias = 0,
}
defineMaterial{
	name = "glass_frame_green_03",
	diffuseMap = "mod_assets/textures/env/glass_doors/glass_frame_green_03_diff.tga",
	specularMap = "mod_assets/textures/env/glass_doors/glass_frame_03_spec.tga",
	normalMap = "mod_assets/textures/env/glass_doors/glass_frame_03_normal.tga",
	doubleSided = false,
	lighting = false,
	alphaTest = true,
	blendMode = "Translucent",
	textureAddressMode = "Wrap",
	glossiness = 1,
	depthBias = 0,
}
defineMaterial{
	name = "glass_frame_green_04",
	diffuseMap = "mod_assets/textures/env/glass_doors/glass_frame_green_04_diff.tga",
	specularMap = "mod_assets/textures/env/glass_doors/glass_frame_04_spec.tga",
	normalMap = "mod_assets/textures/env/glass_doors/glass_frame_04_normal.tga",
	doubleSided = false,
	lighting = false,
	alphaTest = true,
	blendMode = "Translucent",
	textureAddressMode = "Wrap",
	glossiness = 1,
	depthBias = 0,
}
defineMaterial{
	name = "glass_frame_green_05",
	diffuseMap = "mod_assets/textures/env/glass_doors/glass_frame_green_05_diff.tga",
	specularMap = "mod_assets/textures/env/glass_doors/glass_frame_05_spec.tga",
	normalMap = "mod_assets/textures/env/glass_doors/glass_frame_05_normal.tga",
	doubleSided = false,
	lighting = false,
	alphaTest = true,
	blendMode = "Translucent",
	textureAddressMode = "Wrap",
	glossiness = 1,
	depthBias = 0,
}
defineMaterial{
	name = "glass_frame_green_06",
	diffuseMap = "mod_assets/textures/env/glass_doors/glass_frame_green_06_diff.tga",
	specularMap = "mod_assets/textures/env/glass_doors/glass_frame_06_spec.tga",
	normalMap = "mod_assets/textures/env/glass_doors/glass_frame_06_normal.tga",
	doubleSided = false,
	lighting = false,
	alphaTest = true,
	blendMode = "Translucent",
	textureAddressMode = "Wrap",
	glossiness = 1,
	depthBias = 0,
}
defineMaterial{
	name = "glass_frame_green_07",
	diffuseMap = "mod_assets/textures/env/glass_doors/glass_frame_green_07_diff.tga",
	specularMap = "mod_assets/textures/env/glass_doors/glass_frame_07_spec.tga",
	normalMap = "mod_assets/textures/env/glass_doors/glass_frame_07_normal.tga",
	doubleSided = false,
	lighting = false,
	alphaTest = true,
	blendMode = "Translucent",
	textureAddressMode = "Wrap",
	glossiness = 1,
	depthBias = 0,
}
defineMaterial{
	name = "glass_frame_green_08",
	diffuseMap = "mod_assets/textures/env/glass_doors/glass_frame_green_08_diff.tga",
	specularMap = "mod_assets/textures/env/glass_doors/glass_frame_08_spec.tga",
	normalMap = "mod_assets/textures/env/glass_doors/glass_frame_08_normal.tga",
	doubleSided = false,
	lighting = false,
	alphaTest = true,
	blendMode = "Translucent",
	textureAddressMode = "Wrap",
	glossiness = 1,
	depthBias = 0,
}
-- Yellow Glass
defineMaterial{
	name = "glass_frame_yellow_01",
	diffuseMap = "mod_assets/textures/env/glass_doors/glass_frame_yellow_01_diff.tga",
	specularMap = "mod_assets/textures/env/glass_doors/glass_frame_01_spec.tga",
	normalMap = "mod_assets/textures/env/glass_doors/glass_frame_01_normal.tga",
	doubleSided = false,
	lighting = false,
	alphaTest = true,
	blendMode = "Translucent",
	textureAddressMode = "Wrap",
	glossiness = 1,
	depthBias = 0,
}
defineMaterial{
	name = "glass_frame_yellow_02",
	diffuseMap = "mod_assets/textures/env/glass_doors/glass_frame_yellow_02_diff.tga",
	specularMap = "mod_assets/textures/env/glass_doors/glass_frame_02_spec.tga",
	normalMap = "mod_assets/textures/env/glass_doors/glass_frame_02_normal.tga",
	doubleSided = false,
	lighting = false,
	alphaTest = true,
	blendMode = "Translucent",
	textureAddressMode = "Wrap",
	glossiness = 1,
	depthBias = 0,
}
defineMaterial{
	name = "glass_frame_yellow_03",
	diffuseMap = "mod_assets/textures/env/glass_doors/glass_frame_yellow_03_diff.tga",
	specularMap = "mod_assets/textures/env/glass_doors/glass_frame_03_spec.tga",
	normalMap = "mod_assets/textures/env/glass_doors/glass_frame_03_normal.tga",
	doubleSided = false,
	lighting = false,
	alphaTest = true,
	blendMode = "Translucent",
	textureAddressMode = "Wrap",
	glossiness = 1,
	depthBias = 0,
}
defineMaterial{
	name = "glass_frame_yellow_04",
	diffuseMap = "mod_assets/textures/env/glass_doors/glass_frame_yellow_04_diff.tga",
	specularMap = "mod_assets/textures/env/glass_doors/glass_frame_04_spec.tga",
	normalMap = "mod_assets/textures/env/glass_doors/glass_frame_04_normal.tga",
	doubleSided = false,
	lighting = false,
	alphaTest = true,
	blendMode = "Translucent",
	textureAddressMode = "Wrap",
	glossiness = 1,
	depthBias = 0,
}
defineMaterial{
	name = "glass_frame_yellow_05",
	diffuseMap = "mod_assets/textures/env/glass_doors/glass_frame_yellow_05_diff.tga",
	specularMap = "mod_assets/textures/env/glass_doors/glass_frame_05_spec.tga",
	normalMap = "mod_assets/textures/env/glass_doors/glass_frame_05_normal.tga",
	doubleSided = false,
	lighting = false,
	alphaTest = true,
	blendMode = "Translucent",
	textureAddressMode = "Wrap",
	glossiness = 1,
	depthBias = 0,
}
defineMaterial{
	name = "glass_frame_yellow_06",
	diffuseMap = "mod_assets/textures/env/glass_doors/glass_frame_yellow_06_diff.tga",
	specularMap = "mod_assets/textures/env/glass_doors/glass_frame_06_spec.tga",
	normalMap = "mod_assets/textures/env/glass_doors/glass_frame_06_normal.tga",
	doubleSided = false,
	lighting = false,
	alphaTest = true,
	blendMode = "Translucent",
	textureAddressMode = "Wrap",
	glossiness = 1,
	depthBias = 0,
}
defineMaterial{
	name = "glass_frame_yellow_07",
	diffuseMap = "mod_assets/textures/env/glass_doors/glass_frame_yellow_07_diff.tga",
	specularMap = "mod_assets/textures/env/glass_doors/glass_frame_07_spec.tga",
	normalMap = "mod_assets/textures/env/glass_doors/glass_frame_07_normal.tga",
	doubleSided = false,
	lighting = false,
	alphaTest = true,
	blendMode = "Translucent",
	textureAddressMode = "Wrap",
	glossiness = 1,
	depthBias = 0,
}
defineMaterial{
	name = "glass_frame_yellow_08",
	diffuseMap = "mod_assets/textures/env/glass_doors/glass_frame_yellow_08_diff.tga",
	specularMap = "mod_assets/textures/env/glass_doors/glass_frame_08_spec.tga",
	normalMap = "mod_assets/textures/env/glass_doors/glass_frame_08_normal.tga",
	doubleSided = false,
	lighting = false,
	alphaTest = true,
	blendMode = "Translucent",
	textureAddressMode = "Wrap",
	glossiness = 1,
	depthBias = 0,
}

-- Blue Glass
defineMaterial{
	name = "glass_frame_blue_01",
	diffuseMap = "mod_assets/textures/env/glass_doors/glass_frame_blue_01_diff.tga",
	specularMap = "mod_assets/textures/env/glass_doors/glass_frame_01_spec.tga",
	normalMap = "mod_assets/textures/env/glass_doors/glass_frame_01_normal.tga",
	doubleSided = false,
	lighting = false,
	alphaTest = true,
	blendMode = "Translucent",
	textureAddressMode = "Wrap",
	glossiness = 1,
	depthBias = 0,
}
defineMaterial{
	name = "glass_frame_blue_02",
	diffuseMap = "mod_assets/textures/env/glass_doors/glass_frame_blue_02_diff.tga",
	specularMap = "mod_assets/textures/env/glass_doors/glass_frame_02_spec.tga",
	normalMap = "mod_assets/textures/env/glass_doors/glass_frame_02_normal.tga",
	doubleSided = false,
	lighting = false,
	alphaTest = true,
	blendMode = "Translucent",
	textureAddressMode = "Wrap",
	glossiness = 1,
	depthBias = 0,
}
defineMaterial{
	name = "glass_frame_blue_03",
	diffuseMap = "mod_assets/textures/env/glass_doors/glass_frame_blue_03_diff.tga",
	specularMap = "mod_assets/textures/env/glass_doors/glass_frame_03_spec.tga",
	normalMap = "mod_assets/textures/env/glass_doors/glass_frame_03_normal.tga",
	doubleSided = false,
	lighting = false,
	alphaTest = true,
	blendMode = "Translucent",
	textureAddressMode = "Wrap",
	glossiness = 1,
	depthBias = 0,
}
defineMaterial{
	name = "glass_frame_blue_04",
	diffuseMap = "mod_assets/textures/env/glass_doors/glass_frame_blue_04_diff.tga",
	specularMap = "mod_assets/textures/env/glass_doors/glass_frame_04_spec.tga",
	normalMap = "mod_assets/textures/env/glass_doors/glass_frame_04_normal.tga",
	doubleSided = false,
	lighting = false,
	alphaTest = true,
	blendMode = "Translucent",
	textureAddressMode = "Wrap",
	glossiness = 1,
	depthBias = 0,
}
defineMaterial{
	name = "glass_frame_blue_05",
	diffuseMap = "mod_assets/textures/env/glass_doors/glass_frame_blue_05_diff.tga",
	specularMap = "mod_assets/textures/env/glass_doors/glass_frame_05_spec.tga",
	normalMap = "mod_assets/textures/env/glass_doors/glass_frame_05_normal.tga",
	doubleSided = false,
	lighting = false,
	alphaTest = true,
	blendMode = "Translucent",
	textureAddressMode = "Wrap",
	glossiness = 1,
	depthBias = 0,
}
defineMaterial{
	name = "glass_frame_blue_06",
	diffuseMap = "mod_assets/textures/env/glass_doors/glass_frame_blue_06_diff.tga",
	specularMap = "mod_assets/textures/env/glass_doors/glass_frame_06_spec.tga",
	normalMap = "mod_assets/textures/env/glass_doors/glass_frame_06_normal.tga",
	doubleSided = false,
	lighting = false,
	alphaTest = true,
	blendMode = "Translucent",
	textureAddressMode = "Wrap",
	glossiness = 1,
	depthBias = 0,
}
defineMaterial{
	name = "glass_frame_blue_07",
	diffuseMap = "mod_assets/textures/env/glass_doors/glass_frame_blue_07_diff.tga",
	specularMap = "mod_assets/textures/env/glass_doors/glass_frame_07_spec.tga",
	normalMap = "mod_assets/textures/env/glass_doors/glass_frame_07_normal.tga",
	doubleSided = false,
	lighting = false,
	alphaTest = true,
	blendMode = "Translucent",
	textureAddressMode = "Wrap",
	glossiness = 1,
	depthBias = 0,
}
defineMaterial{
	name = "glass_frame_blue_08",
	diffuseMap = "mod_assets/textures/env/glass_doors/glass_frame_blue_08_diff.tga",
	specularMap = "mod_assets/textures/env/glass_doors/glass_frame_08_spec.tga",
	normalMap = "mod_assets/textures/env/glass_doors/glass_frame_08_normal.tga",
	doubleSided = false,
	lighting = false,
	alphaTest = true,
	blendMode = "Translucent",
	textureAddressMode = "Wrap",
	glossiness = 1,
	depthBias = 0,
}
-- Red Glass
defineMaterial{
	name = "glass_frame_red_01",
	diffuseMap = "mod_assets/textures/env/glass_doors/glass_frame_red_01_diff.tga",
	specularMap = "mod_assets/textures/env/glass_doors/glass_frame_01_spec.tga",
	normalMap = "mod_assets/textures/env/glass_doors/glass_frame_01_normal.tga",
	doubleSided = false,
	lighting = false,
	alphaTest = true,
	blendMode = "Translucent",
	textureAddressMode = "Wrap",
	glossiness = 1,
	depthBias = 0,
}
defineMaterial{
	name = "glass_frame_red_02",
	diffuseMap = "mod_assets/textures/env/glass_doors/glass_frame_red_02_diff.tga",
	specularMap = "mod_assets/textures/env/glass_doors/glass_frame_02_spec.tga",
	normalMap = "mod_assets/textures/env/glass_doors/glass_frame_02_normal.tga",
	doubleSided = false,
	lighting = false,
	alphaTest = true,
	blendMode = "Translucent",
	textureAddressMode = "Wrap",
	glossiness = 1,
	depthBias = 0,
}
defineMaterial{
	name = "glass_frame_red_03",
	diffuseMap = "mod_assets/textures/env/glass_doors/glass_frame_red_03_diff.tga",
	specularMap = "mod_assets/textures/env/glass_doors/glass_frame_03_spec.tga",
	normalMap = "mod_assets/textures/env/glass_doors/glass_frame_03_normal.tga",
	doubleSided = false,
	lighting = false,
	alphaTest = true,
	blendMode = "Translucent",
	textureAddressMode = "Wrap",
	glossiness = 1,
	depthBias = 0,
}
defineMaterial{
	name = "glass_frame_red_04",
	diffuseMap = "mod_assets/textures/env/glass_doors/glass_frame_red_04_diff.tga",
	specularMap = "mod_assets/textures/env/glass_doors/glass_frame_04_spec.tga",
	normalMap = "mod_assets/textures/env/glass_doors/glass_frame_04_normal.tga",
	doubleSided = false,
	lighting = false,
	alphaTest = true,
	blendMode = "Translucent",
	textureAddressMode = "Wrap",
	glossiness = 1,
	depthBias = 0,
}
defineMaterial{
	name = "glass_frame_red_05",
	diffuseMap = "mod_assets/textures/env/glass_doors/glass_frame_red_05_diff.tga",
	specularMap = "mod_assets/textures/env/glass_doors/glass_frame_05_spec.tga",
	normalMap = "mod_assets/textures/env/glass_doors/glass_frame_05_normal.tga",
	doubleSided = false,
	lighting = false,
	alphaTest = true,
	blendMode = "Translucent",
	textureAddressMode = "Wrap",
	glossiness = 1,
	depthBias = 0,
}
defineMaterial{
	name = "glass_frame_red_06",
	diffuseMap = "mod_assets/textures/env/glass_doors/glass_frame_red_06_diff.tga",
	specularMap = "mod_assets/textures/env/glass_doors/glass_frame_06_spec.tga",
	normalMap = "mod_assets/textures/env/glass_doors/glass_frame_06_normal.tga",
	doubleSided = false,
	lighting = false,
	alphaTest = true,
	blendMode = "Translucent",
	textureAddressMode = "Wrap",
	glossiness = 1,
	depthBias = 0,
}
defineMaterial{
	name = "glass_frame_red_07",
	diffuseMap = "mod_assets/textures/env/glass_doors/glass_frame_red_07_diff.tga",
	specularMap = "mod_assets/textures/env/glass_doors/glass_frame_07_spec.tga",
	normalMap = "mod_assets/textures/env/glass_doors/glass_frame_07_normal.tga",
	doubleSided = false,
	lighting = false,
	alphaTest = true,
	blendMode = "Translucent",
	textureAddressMode = "Wrap",
	glossiness = 1,
	depthBias = 0,
}
defineMaterial{
	name = "glass_frame_red_08",
	diffuseMap = "mod_assets/textures/env/glass_doors/glass_frame_red_08_diff.tga",
	specularMap = "mod_assets/textures/env/glass_doors/glass_frame_08_spec.tga",
	normalMap = "mod_assets/textures/env/glass_doors/glass_frame_08_normal.tga",
	doubleSided = false,
	lighting = false,
	alphaTest = true,
	blendMode = "Translucent",
	textureAddressMode = "Wrap",
	glossiness = 1,
	depthBias = 0,
}