-- This file has been generated by Dungeon Editor 1.3.7

-- import standard assets
import "assets/scripts/standard_assets.lua"

-- import grimwidgets
--import("mod_assets/framework/framework.lua")
import "mod_assets/grimwidgets/grimwidgets.lua"
import "mod_assets/ai/aiswitcher.lua"



-- import custom assets
import "mod_assets/scripts/items.lua"
import "mod_assets/scripts/monsters.lua"
import "mod_assets/scripts/objects.lua"
import "mod_assets/scripts/wall_sets.lua"
import "mod_assets/scripts/recipes.lua"
import "mod_assets/scripts/spells.lua"
import "mod_assets/scripts/materials.lua"
import "mod_assets/scripts/sounds.lua"
import "mod_assets/scripts/monster_special.lua"

import "mod_assets/scripts/secret_doors_extras.lua"
import "mod_assets/scripts/sx_extra_lanterns.lua"
import "mod_assets/sx_water_fountains/scripts/sx_waterfountains.lua"
import "mod_assets/scripts/boulder.lua"
import "mod_assets/scripts/flooded_dungeon.lua"
import "mod_assets/scripts/skeletons_impaled.lua"
import "mod_assets/scripts/party.lua"
import "mod_assets/log_desk/log_desk.lua"
import "mod_assets/grim_sqtable/grim_sqtable.lua"
import "mod_assets/grim_bed/grim_bed.lua"
import "mod_assets/scripts/clean_dungeon_objects.lua"
import "mod_assets/scripts/clean_dungeon_materials.lua"
import "mod_assets/scripts/clean_dungeon_wallset.lua"
import "mod_assets/scripts/glass_walls_and_secret_doors.lua"
import "mod_assets/pandafox_assets/skeleton_ghost/skeleton_ghost.lua"
import "mod_assets/scripts/alcoves.lua"
import "mod_assets/scripts/particles.lua"
import "mod_assets/scripts/alcoves_and_gems_collection.lua"
import "mod_assets/scripts/up.lua"
import "mod_assets/scripts/buttons.lua"


import "mod_assets/exsp/exsp_init.lua"