-- This file has been generated by Dungeon Editor 1.3.7

-- TODO: place your custom item definitions here

	defineObject{
		name = "blue_gem_fake",
		class = "Item",
		uiName = "Blue Gem",
		model = "assets/models/items/blue_gem.fbx",
		gfxIndex = 118,
		weight = 0.2,
	}
	defineObject{
		name = "green_gem_fake",
		class = "Item",
		uiName = "Green Gem",
		model = "assets/models/items/green_gem.fbx",
		gfxIndex = 119,
		weight = 0.2,
	}
	
	defineObject{
	name = "itm_gem_green_01_fake",
	class = "Item",
	uiName = "Emerald",
	description = "An emerald.",
	model = "mod_assets/models/items/gems/gem_green_01.fbx",
	gfxAtlas = "mod_assets/textures/gui/gui_icons_gems.tga",
	gfxIndex = 63,
	weight = 0.1,
}
defineObject{
	name = "itm_gem_blue_01_fake",
	class = "Item",
	uiName = "Sapphire",
	description = "A sapphire.",
	model = "mod_assets/models/items/gems/gem_blue_01.fbx",
	gfxAtlas = "mod_assets/textures/gui/gui_icons_gems.tga",
	gfxIndex = 49,
	weight = 0.1,
}
defineObject{
	name = "itm_gem_red_01_fake",
	class = "Item",
	uiName = "Ruby",
	description = "A Ruby.",
	model = "mod_assets/models/items/gems/gem_red_01.fbx",
	gfxAtlas = "mod_assets/textures/gui/gui_icons_gems.tga",
	gfxIndex = 14,
	weight = 0.1,
}
defineObject{
	name = "itm_gem_yellow_01_fake",
	class = "Item",
	uiName = "Citrine",
	description = "A yellow citrine.",
	model = "mod_assets/models/items/gems/gem_yellow_01.fbx",
	gfxAtlas = "mod_assets/textures/gui/gui_icons_gems.tga",
	gfxIndex = 98,
	weight = 0.1,
}
	
defineObject{
	name = "itm_gem_white_01_fake",
	class = "Item",
	uiName = "Diamond",
	description = "A Diamond.",
	model = "mod_assets/models/items/gems/gem_white_01.fbx",
	gfxAtlas = "mod_assets/textures/gui/gui_icons_gems.tga",
	gfxIndex = 0,
	weight = 0.1,
}	
	
defineObject{
	name = "itm_gem_white_02_fake",
	class = "Item",
	uiName = "Diamond",
	description = "A Diamond.",
	model = "mod_assets/models/items/gems/gem_white_02.fbx",
	gfxAtlas = "mod_assets/textures/gui/gui_icons_gems.tga",
	gfxIndex = 1,
	weight = 0.1,
}	

defineObject{
	name = "itm_gem_white_06_fake",
	class = "Item",
	uiName = "Diamond",
	description = "A Diamond.",
	model = "mod_assets/models/items/gems/gem_white_06.fbx",
	gfxAtlas = "mod_assets/textures/gui/gui_icons_gems.tga",
	gfxIndex = 5,
	weight = 0.1,
}

	
defineObject{
		name = "horned_skull",
		class = "Item",
                gfxAtlas = "mod_assets/textures/icons/items_s.tga",
		uiName = "Horned Skull",
		model = "mod_assets/models/horned_skull.fbx",
		gfxIndex = 32,
		weight = 1.0,
	}

defineObject{
		name = "bloody_skull",
		class = "Item",
                gfxAtlas = "mod_assets/textures/icons/items_s.tga",
		uiName = "Bloody Skull",
		model = "mod_assets/models/bloody_skull.fbx",
		gfxIndex = 31,
		weight = 1.0,
	}

defineObject{
		name = "blood_soaked_skull",
		class = "Item",
                gfxAtlas = "mod_assets/textures/icons/items_s.tga",
		uiName = "Blood Soaked Skull",
		model = "mod_assets/models/blood_soaked_skull.fbx",
		gfxIndex = 30,
		weight = 1.0,
	}

defineObject{
		name = "stone_skull",
		class = "Item",
                gfxAtlas = "mod_assets/textures/icons/items_s.tga",
		uiName = "Stone Skull",
		model = "mod_assets/models/stone_skull.fbx",
		gfxIndex = 29,
		weight = 1.0,
	}	
	
defineObject{
		name = "skull_horned_fake",
		class = "Item",
                gfxAtlas = "mod_assets/textures/icons/items_s.tga",
		uiName = "Horned Skull",
		model = "mod_assets/models/horned_skull.fbx",
		gfxIndex = 32,
		weight = 1.0,
	}

defineObject{
		name = "skull_bloody_fake",
		class = "Item",
                gfxAtlas = "mod_assets/textures/icons/items_s.tga",
		uiName = "Bloody Skull",
		model = "mod_assets/models/bloody_skull.fbx",
		gfxIndex = 31,
		weight = 1.0,
	}

defineObject{
		name = "skull_blood_soaked_fake",
		class = "Item",
                gfxAtlas = "mod_assets/textures/icons/items_s.tga",
		uiName = "Blood Soaked Skull",
		model = "mod_assets/models/blood_soaked_skull.fbx",
		gfxIndex = 30,
		weight = 1.0,
	}

defineObject{
		name = "skull_stone_fake",
		class = "Item",
                gfxAtlas = "mod_assets/textures/icons/items_s.tga",
		uiName = "Stone Skull",
		model = "mod_assets/models/stone_skull.fbx",
		gfxIndex = 29,
		weight = 1.0,
	}		
defineObject{
		name = "skull_fake",
		class = "Item",
		uiName = "Skull",
		model = "assets/models/items/skull.fbx",
		gfxIndex = 31,
		weight = 1.0,
	}	
	
	
	
cloneObject{
	name = "green_lizard_steak",
	baseObject = "ice_lizard_steak",
	uiName = "Green Lizard Steak",
	model = "mod_assets/models/green_lizard_steak.fbx",
	gfxAtlas = "mod_assets/textures/akroma_icon_atlas.tga",
	gfxIndex = 1,
	consumable = true,
	nutritionValue = 750,
	weight = 2.2,
}

cloneObject{
	name = "fire_lizard_steak",
	baseObject = "ice_lizard_steak",
	uiName = "Fire Lizard Steak",
	model = "mod_assets/models/fire_lizard_steak.fbx",
	gfxAtlas = "mod_assets/textures/akroma_icon_atlas.tga",
	gfxIndex = 0,
	consumable = true,
	nutritionValue = 750,
	weight = 2.2,
}

cloneObject{
	name = "dark_lizard_steak",
	baseObject = "ice_lizard_steak",
	uiName = "Dark Lizard Steak",
	model = "mod_assets/models/dark_lizard_steak.fbx",
	gfxAtlas = "mod_assets/textures/akroma_icon_atlas.tga",
	gfxIndex = 2,
	consumable = true,
	nutritionValue = 750,
	weight = 2.2,
}

cloneObject{
	name = "legionary_spear_dark",
	baseObject ="legionary_spear",
	uiName = "Dark Legion Spear",
	model = "mod_assets/models/skeleton_dark_spear.fbx",
	gfxAtlas = "mod_assets/textures/akroma_icon_atlas.tga",
	gfxIndex = 4,
	attackPower = 20,
	accuracy = 5,
	coolDownTime = 4,
	attackMethod = "meleeAttack",
	attackSwipe = "thrust",
	attackSound = "swipe",
	impactSound = "impact_blade",
	weight = 3.0,
	reachWeapon = true,
}

cloneObject{
	name = "legionary_shield_dark",
	baseObject = "legionary_shield",
	uiName = "Dark Legion Shield",
	model = "mod_assets/models/skeleton_dark_shield.fbx",
	gfxAtlas = "mod_assets/textures/akroma_icon_atlas.tga",
	gfxIndex = 3,
	evasion = 10,
	weight = 7.5,
	shield = true,
}

cloneObject{
	name = "ogre_red_horn_hammer",
	baseObject = "ogre_hammer",
	uiName = "Bloody Maul",
	model = "mod_assets/models/ogre_red_horn_hammer.fbx",
	gfxAtlas = "mod_assets/textures/akroma_icon_atlas_publicV1.0.tga",
	gfxIndex = 5,
}	
	
defineObject{
      name = "spider_web",
      class = "Item",
      uiName = "Spider Web",
      model = "mod_assets/models/spider_web.fbx",                     
      skill = "throwing_weapons",
      ammoType = "rock",
      throwingWeapon = true,
      gfxIndex = 45,
      attackPower = 5,
      coolDownTime = 4,
      attackMethod = "throwAttack",
      attackSound = "swipe",
      impactSound = "impact_blunt",
      stackable = true,
      projectileRotationSpeed = 0,
      projectileRotationZ = 0,
      weight = 1.0,

}	
	
defineObject{
      name = "egg_poison",
      class = "Item",
      uiName = "Egg Poison",
      model = "mod_assets/models/egg_poison.fbx",                     
      skill = "throwing_weapons",
      ammoType = "rock",
      throwingWeapon = true,
      gfxIndex = 45,
      attackPower = 5,
      coolDownTime = 4,
      attackMethod = "throwAttack",
      attackSound = "swipe",
      impactSound = "impact_blunt",
      stackable = true,
      projectileRotationSpeed = 10,
      projectileRotationZ = -30,
      weight = 1.0,

}
defineObject{
      name = "snail_projectile",
      class = "Item",
      uiName = "Snail Projectile",
      model = "mod_assets/models/snail_projectile.fbx",                     
      skill = "throwing_weapons",
      ammoType = "rock",
      throwingWeapon = true,
      gfxIndex = 45,
      attackPower = 5,
      coolDownTime = 4,
      attackMethod = "throwAttack",
      attackSound = "swipe",
      impactSound = "impact_blunt",
      stackable = true,

      weight = 1.0,

}	
	
