-- This file has been generated by Dungeon Editor 1.3.7

-- TODO: place your custom material definitions here
defineMaterial{
	name = "boulder",

	diffuseMap = "assets/textures/env/rockwall_tile_light_dif.tga",

	specularMap = "assets/textures/env/rockwall_tile_spec.tga",

	doubleSided = false,

	lighting = true,

	alphaTest = false,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = 20,

	depthBias = 0,

}


defineMaterial{

	name = "splotchy_dungeon_wall",

	diffuseMap = "mod_assets/textures/new_textures/splotchy_dungeon_wall_dif.tga",

	specularMap = "assets/textures/env/brickwall_stone_root_spec.tga",

	normalMap = "assets/textures/env/brickwall_stone_root_normal.tga",

	doubleSided = false,

	lighting = true,

	alphaTest = false,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = 15,

	depthBias = 0,

}


defineMaterial{

	name = "mosswall_symbol8",

	diffuseMap = "mod_assets/textures/new_textures/dungeon_wall_moss_symbol8.tga",

	specularMap = "assets/textures/env/brickwall_stone_root_spec.tga",

	normalMap = "assets/textures/env/brickwall_stone_root_normal.tga",

	doubleSided = false,

	lighting = true,

	alphaTest = false,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = 15,

	depthBias = 0,

}


defineMaterial{

	name = "mosswall_symbol7",

	diffuseMap = "mod_assets/textures/new_textures/dungeon_wall_moss_symbol7.tga",

	specularMap = "assets/textures/env/brickwall_stone_root_spec.tga",

	normalMap = "assets/textures/env/brickwall_stone_root_normal.tga",

	doubleSided = false,

	lighting = true,

	alphaTest = false,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = 15,

	depthBias = 0,

}

defineMaterial{

	name = "mosswall_symbol6",

	diffuseMap = "mod_assets/textures/new_textures/dungeon_wall_moss_symbol6.tga",

	specularMap = "assets/textures/env/brickwall_stone_root_spec.tga",

	normalMap = "assets/textures/env/brickwall_stone_root_normal.tga",

	doubleSided = false,

	lighting = true,

	alphaTest = false,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = 15,

	depthBias = 0,

}

defineMaterial{

	name = "mosswall_symbol5",

	diffuseMap = "mod_assets/textures/new_textures/dungeon_wall_moss_symbol5.tga",

	specularMap = "assets/textures/env/brickwall_stone_root_spec.tga",

	normalMap = "assets/textures/env/brickwall_stone_root_normal.tga",

	doubleSided = false,

	lighting = true,

	alphaTest = false,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = 15,

	depthBias = 0,

}


defineMaterial{

	name = "mosswall_symbol4",

	diffuseMap = "mod_assets/textures/new_textures/dungeon_wall_moss_symbol4.tga",

	specularMap = "assets/textures/env/brickwall_stone_root_spec.tga",

	normalMap = "assets/textures/env/brickwall_stone_root_normal.tga",

	doubleSided = false,

	lighting = true,

	alphaTest = false,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = 15,

	depthBias = 0,

}


defineMaterial{

	name = "mosswall_symbol3",

	diffuseMap = "mod_assets/textures/new_textures/dungeon_wall_moss_symbol3.tga",

	specularMap = "assets/textures/env/brickwall_stone_root_spec.tga",

	normalMap = "assets/textures/env/brickwall_stone_root_normal.tga",

	doubleSided = false,

	lighting = true,

	alphaTest = false,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = 15,

	depthBias = 0,

}

defineMaterial{

	name = "mosswall_symbol2",

	diffuseMap = "mod_assets/textures/new_textures/dungeon_wall_moss_symbol2.tga",

	specularMap = "assets/textures/env/brickwall_stone_root_spec.tga",

	normalMap = "assets/textures/env/brickwall_stone_root_normal.tga",

	doubleSided = false,

	lighting = true,

	alphaTest = false,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = 15,

	depthBias = 0,

}


defineMaterial{

	name = "mosswall_symbol1",

	diffuseMap = "mod_assets/textures/new_textures/dungeon_wall_moss_symbol1.tga",

	specularMap = "assets/textures/env/brickwall_stone_root_spec.tga",

	normalMap = "assets/textures/env/brickwall_stone_root_normal.tga",

	doubleSided = false,

	lighting = true,

	alphaTest = false,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = 15,

	depthBias = 0,

}

defineMaterial{
	name = "gobelin_tricorne",
	diffuseMap = "mod_assets/textures/gobelin/gobelin_tricorne_dif.tga",
	specularMap = "assets/textures/env/dungeon_gobelin_spec.tga",
	normalMap = "assets/textures/env/dungeon_gobelin_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = true,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 20,
	depthBias = 0,
}

defineMaterial{
	name = "gobelin_tricorne_torn",
	diffuseMap = "mod_assets/textures/gobelin/gobelin_tricorne_torn_dif.tga",
	specularMap = "assets/textures/env/dungeon_gobelin_torn_spec.tga",
	normalMap = "assets/textures/env/dungeon_gobelin_torn_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = true,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 20,
	depthBias = 0,
}

	
defineMaterial{
	name = "gobelin_wolfcircle",
	diffuseMap = "mod_assets/textures/gobelin/gobelin_wolfcircle_dif.tga",
	specularMap = "assets/textures/env/dungeon_gobelin_spec.tga",
	normalMap = "assets/textures/env/dungeon_gobelin_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = true,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 10,
	depthBias = 0,
}

defineMaterial{
	name = "gobelin_wolfcircle_torn",
	diffuseMap = "mod_assets/textures/gobelin/gobelin_wolfcircle_torn_dif.tga",
	specularMap = "assets/textures/env/dungeon_gobelin_torn_spec.tga",
	normalMap = "assets/textures/env/dungeon_gobelin_torn_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = true,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 10,
	depthBias = 0,
}

defineMaterial{
	name = "gobelin_sacrifice",
	diffuseMap = "mod_assets/textures/gobelin/gobelin_sacrifice_dif.tga",
	specularMap = "assets/textures/env/dungeon_gobelin_spec.tga",
	normalMap = "assets/textures/env/dungeon_gobelin_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = true,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 7,
	depthBias = 0,
}

defineMaterial{
	name = "gobelin_sacrifice_torn",
	diffuseMap = "mod_assets/textures/gobelin/gobelin_sacrifice_torn_dif.tga",
	specularMap = "assets/textures/env/dungeon_gobelin_torn_spec.tga",
	normalMap = "assets/textures/env/dungeon_gobelin_torn_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = true,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 7,
	depthBias = 0,
}

defineMaterial{
	name = "gobelin_wheel",
	diffuseMap = "mod_assets/textures/gobelin/gobelin_wheel_dif.tga",
	specularMap = "assets/textures/env/dungeon_gobelin_spec.tga",
	normalMap = "assets/textures/env/dungeon_gobelin_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = true,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 7,
	depthBias = 0,
}

defineMaterial{
	name = "gobelin_wheel_torn",
	diffuseMap = "mod_assets/textures/gobelin/gobelin_wheel_torn_dif.tga",
	specularMap = "assets/textures/env/dungeon_gobelin_torn_spec.tga",
	normalMap = "assets/textures/env/dungeon_gobelin_torn_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = true,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 7,
	depthBias = 0,
}

defineMaterial{
	
	name = "boulder_roll",
	
	diffuseMap = "mod_assets/textures/boulder.tga",
	
	specularMap  = "mod_assets/textures/boulder_spec.tga",
	normalMap  = "mod_assets/textures/boulder_normal.tga",	
	doubleSided = false,
	
	lighting = true,
	
	alphaTest = false,
	
	blendMode = "Opaque",
	
	textureAddressMode = "Wrap",
	
	glossiness = 85,
	
	depthBias = 0,

}


defineMaterial{

	name = "ast_dwarf_altar",

	diffuseMap = "mod_assets/textures/ast_dwarf_altar_dif.tga",

	specularMap = "assets/textures/env/dungeon_altar_spec.tga",

	normalMap = "assets/textures/env/dungeon_altar_normal.tga",

	doubleSided = false,

	lighting = true,

	alphaTest = false,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = 30,

	depthBias = 0,

}


defineMaterial{

	name = "ast_dwarf_hammer_altar",

	diffuseMap = "mod_assets/textures/ast_dwarf_hammer_altar_dif.tga",

	specularMap = "assets/textures/env/dungeon_altar_spec.tga",

	normalMap = "assets/textures/env/dungeon_altar_normal.tga",

	doubleSided = false,

	lighting = true,

	alphaTest = false,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = 30,

	depthBias = 0,

}


defineMaterial{

	name = "impaled_skull",

	diffuseMap = "mod_assets/textures/impaled_skull_dif.tga",

	specularMap = "assets/textures/props/human_skull_spec.tga",

	normalMap = "assets/textures/props/human_skull_normal.tga",

	doubleSided = false,

	lighting = true,

	alphaTest = false,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = 20,

	depthBias = 0,

}

defineMaterial{

	name = "blood_soaked_skull",

	diffuseMap = "mod_assets/textures/blood_soaked_skull_dif.tga",

	specularMap = "mod_assets/textures/special_skull_spec.tga",

	normalMap = "assets/textures/props/human_skull_normal.tga",

	doubleSided = false,

	lighting = true,

	alphaTest = false,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = 20,

	depthBias = 0,

}

defineMaterial{

	name = "bloody_skull",

	diffuseMap = "mod_assets/textures/bloody_skull_dif.tga",

	specularMap = "mod_assets/textures/special_skull_spec.tga",

	normalMap = "assets/textures/props/human_skull_normal.tga",

	doubleSided = false,

	lighting = true,

	alphaTest = false,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = 20,

	depthBias = 0,

}

defineMaterial{

	name = "stone_skull",

	diffuseMap = "mod_assets/textures/stone_skull_dif.tga",

	specularMap = "mod_assets/textures/stone_skull_spec.tga",

	normalMap = "assets/textures/props/human_skull_normal.tga",

	doubleSided = false,

	lighting = true,

	alphaTest = false,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = 20,

	depthBias = 0,

}

defineMaterial{
	name = "practice_dummy",
	diffuseMap = "mod_assets/textures/practice_dummy_dif.tga",
	specularMap = "mod_assets/textures/practice_dummy_spec.tga",
	normalMap = "mod_assets/textures/practice_dummy_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 40,
	depthBias = 0,
}

defineMaterial{
	name = "anti_click",
	diffuseMap = "assets/textures/dream/dream_fog_02_dif.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = true,
	blendMode = "Translucent",
	textureAddressMode = "Wrap",
	glossiness = 20,
	depthBias = 0,
}
defineMaterial{
	name = "invisible",
	diffuseMap = "assets/textures/dream/dream_fog_02_dif.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Translucent",
	textureAddressMode = "Wrap",
	glossiness = 60,
	depthBias = 0,
}

defineParticleSystem{
   name = "fog",
   emitters = {

      
      -- fog
      {
         emissionRate = 1.5,
         emissionTime = 0,
         maxParticles = 200,
         boxMin = {-2, 0.1, -2},
         boxMax = { 2, 0.1,  2},
         sprayAngle = {0,30},
         velocity = {0,0},
         texture = "assets/textures/particles/smoke_01.tga",
         lifetime = {10,20},
         color0 = {0.5, 0.5, 0.5},
         opacity = 0.8,
         fadeIn = 9,
         fadeOut = 9,
         size = {4, 8},
         gravity = {0,0,0},
         airResistance = 0.1,
         rotationSpeed = 0.05,
         blendMode = "Translucent",
         objectSpace = false,
      }
   }
}


defineParticleSystem{
name = "dust",
emitters = {


-- dust
{
emissionRate = 55,
emissionTime = 5,
maxParticles = 100,
boxMin = {-2, 0.1, -2},
boxMax = { 2, 1.4, 2},
sprayAngle = {0,45},
velocity = {0,0},
texture = "assets/textures/particles/fog.tga",
lifetime = {10,20},
color0 = {0.25, 0.2, 0.13},
opacity = 0.6,
fadeIn = 0.5,
fadeOut = 7,
size = {1, 5},
gravity = {0,-0.1,0},
airResistance = 0.1,
rotationSpeed = 0.3,
blendMode = "Translucent",
objectSpace = false,
},
{
emissionRate = 45,
emissionTime = 10,
maxParticles = 100,
boxMin = {-2, 0,1,-2},
boxMax = { 2, 3, 2},
sprayAngle = {30,30},
velocity = {0,0},
texture = "assets/textures/particles/fog.tga",
lifetime = {10,20},
color0 = {0.25, 0.2, 0.13},
opacity = 0.6,
fadeIn = 0.3,
fadeOut = 2,
size = {0.1, 0.2},
gravity = {0,-0.75,0},
airResistance = 0.1,
rotationSpeed = 0.3,
blendMode = "Translucent",
}
}
}


defineParticleSystem{
name = "fire",
emitters = {
-- smoke
{
emissionRate = 60,
emissionTime = 0,
maxParticles = 500,
boxMin = {-3, 0.1, -1.5},
boxMax = {0, 2, 1.5},
sprayAngle = {0,30},
velocity = {0.1,0.5},
texture = "assets/textures/particles/smoke_01.tga",
lifetime = {1,1.75},
color0 = {0.15, 0.15, 0.15},
opacity = 0.6,
fadeIn = 0.5,
fadeOut = 0.5,
size = {1, 1.5},
gravity = {0,0,0},
airResistance = 0.1,
rotationSpeed = 0.6,
blendMode = "Translucent",
},

-- flames
{
emissionRate = 600,
emissionTime = 0,
maxParticles = 3000,
boxMin = {-3, -.2, -1.5},
boxMax = {0, 0, 1.5},
sprayAngle = {0,10},
velocity = {0.2, 1},
texture = "assets/textures/particles/torch_flame.tga",
frameRate = 35,
frameSize = 64,
frameCount = 16,
lifetime = {0.25, 0.85},
colorAnimation = true,
color0 = {2, 2, 2},
color1 = {1.0, 1.0, 1.0},
color2 = {1.0, 0.5, 0.25},
color3 = {1.0, 0.3, 0.1},
opacity = 1,
fadeIn = 0.15,
fadeOut = 0.3,
size = {0.15, 1},
gravity = {0,-0.1,0},
airResistance = 1.0,
rotationSpeed = 0.6,
blendMode = "Additive",
depthBias = -0.002,
},

}
}

defineMaterial{
	
	name = "scavenger_red_tooth",
	
	diffuseMap = "mod_assets/textures/scavenger_red_tooth_dif.tga",
	
	specularMap = "assets/textures/monsters/scavenger_spec.tga",
	
	normalMap = "assets/textures/monsters/scavenger_normal.tga",
	
	doubleSided = false,
	
	lighting = true,
	
	alphaTest = false,
	
	blendMode = "Opaque",
	
	textureAddressMode = "Wrap",
	
	glossiness = 25,
	
	depthBias = 0,

}

defineMaterial{
	
	name = "scavenger_black",
	
	diffuseMap = "mod_assets/textures/scavenger_black_dif.tga",
	
	specularMap = "assets/textures/monsters/scavenger_spec.tga",
	
	normalMap = "assets/textures/monsters/scavenger_normal.tga",
	
	doubleSided = false,
	
	lighting = true,
	
	alphaTest = false,
	
	blendMode = "Opaque",
	
	textureAddressMode = "Wrap",
	
	glossiness = 25,
	
	depthBias = 0,

}

defineMaterial{

	name = "skeleton_dark",

	diffuseMap = "mod_assets/textures/skeleton_dark_dif.tga",

	specularMap = "assets/textures/monsters/skeleton_warrior_spec.tga",

	normalMap = "assets/textures/monsters/skeleton_warrior_normal.tga",

	doubleSided = false,

	lighting = true,

	alphaTest = false,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = 75,

	depthBias = 0,

}

defineMaterial{

	name = "skeleton_dark_weapons",

	diffuseMap = "mod_assets/textures/skeleton_dark_weapons_dif.tga",

	specularMap = "assets/textures/monsters/skeleton_warrior_weapons_spec.tga",

	normalMap = "assets/textures/monsters/skeleton_warrior_weapons_normal.tga",

	doubleSided = false,

	lighting = true,

	alphaTest = false,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = 50,

	depthBias = 0,

}

defineMaterial{
	name = "exotic_crab",
	diffuseMap = "mod_assets/textures/exotic_crab_dif.tga",
	specularMap = "assets/textures/monsters/cave_crab_spec.tga",
	normalMap = "assets/textures/monsters/cave_crab_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 65,
	depthBias = 0,
}

defineMaterial{
	name = "exotic_crab_1",
	diffuseMap = "mod_assets/textures/exotic_crab_1_dif.tga",
	specularMap = "assets/textures/monsters/cave_crab_spec.tga",
	normalMap = "assets/textures/monsters/cave_crab_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 65,
	depthBias = 0,
}

defineMaterial{
	name = "exotic_crab_2",
	diffuseMap = "mod_assets/textures/exotic_crab_2_dif.tga",
	specularMap = "assets/textures/monsters/cave_crab_spec.tga",
	normalMap = "assets/textures/monsters/cave_crab_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 65,
	depthBias = 0,
}

defineMaterial{
	name = "exotic_crab_3",
	diffuseMap = "mod_assets/textures/exotic_crab_3_dif.tga",
	specularMap = "assets/textures/monsters/cave_crab_spec.tga",
	normalMap = "assets/textures/monsters/cave_crab_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 65,
	depthBias = 0,
}

defineMaterial{
	
	name = "spider_red",
	
	diffuseMap = "mod_assets/textures/spider_red_dif.tga",
	
	specularMap = "assets/textures/monsters/spider_spec.tga",
	
	normalMap = "assets/textures/monsters/spider_normal.tga",
	
	doubleSided = false,
	
	lighting = true,
	
	alphaTest = false,
	
	blendMode = "Opaque",
	
	textureAddressMode = "Wrap",
	
	glossiness = 45,
	
	depthBias = 0,

}

defineMaterial{
	
	name = "spider_dark_orange",
	
	diffuseMap = "mod_assets/textures/spider_dark_orange_dif.tga",
	
	specularMap = "assets/textures/monsters/spider_spec.tga",
	
	normalMap = "assets/textures/monsters/spider_normal.tga",
	
	doubleSided = false,
	
	lighting = true,
	
	alphaTest = false,
	
	blendMode = "Opaque",
	
	textureAddressMode = "Wrap",
	
	glossiness = 65,
	
	depthBias = 0,

}


defineMaterial{
	
	name = "spider_green",
	
	diffuseMap = "mod_assets/textures/spider_green_dif.tga",
	
	specularMap = "assets/textures/monsters/spider_spec.tga",
	
	normalMap = "assets/textures/monsters/spider_normal.tga",
	
	doubleSided = false,
	
	lighting = true,
	
	alphaTest = false,
	
	blendMode = "Opaque",
	
	textureAddressMode = "Wrap",
	
	glossiness = 45,
	
	depthBias = 0,

}

defineMaterial{
	
	name = "spider_northern",
	
	diffuseMap = "mod_assets/textures/spider_northern_dif.tga",
	
	specularMap = "assets/textures/monsters/spider_spec.tga",
	
	normalMap = "assets/textures/monsters/spider_normal.tga",
	
	doubleSided = false,
	
	lighting = true,
	
	alphaTest = false,
	
	blendMode = "Opaque",
	
	textureAddressMode = "Wrap",
	
	glossiness = 45,
	
	depthBias = 0,

}

defineMaterial{
	
	name = "spider_tropical",
	
	diffuseMap = "mod_assets/textures/spider_tropical_dif.tga",
	
	specularMap = "assets/textures/monsters/spider_spec.tga",
	
	normalMap = "assets/textures/monsters/spider_normal.tga",
	
	doubleSided = false,
	
	lighting = true,
	
	alphaTest = false,
	
	blendMode = "Opaque",
	
	textureAddressMode = "Wrap",
	
	glossiness = 75,
	
	depthBias = 0,

}

defineMaterial{
	
	name = "snail_red_purple",
	
	diffuseMap = "mod_assets/textures/snail_red_purple_dif.tga",
	
	specularMap = "assets/textures/monsters/snail_spec.tga",
	
	normalMap = "assets/textures/monsters/snail_normal.tga",
	
	doubleSided = false,
	
	lighting = true,
	
	alphaTest = false,
	
	blendMode = "Opaque",
	
	textureAddressMode = "Wrap",
	
	glossiness = 100,
	
	depthBias = 0,

}

defineMaterial{
	name = "snail_shell_red_purple",
	
	diffuseMap = "mod_assets/textures/snail_red_purple_dif.tga",
	
	specularMap = "assets/textures/monsters/snail_spec.tga",
	
	normalMap = "assets/textures/monsters/snail_normal.tga",
	
	doubleSided = false,
	
	lighting = true,
	
	alphaTest = false,
	
	blendMode = "Opaque",
	
	textureAddressMode = "Wrap",
	
	glossiness = 40,
	
	depthBias = 0,

}

defineMaterial{
	
	name = "snail_green_brown",
	
	diffuseMap = "mod_assets/textures/snail_green_brown_dif.tga",
	
	specularMap = "assets/textures/monsters/snail_spec.tga",
	
	normalMap = "assets/textures/monsters/snail_normal.tga",
	
	doubleSided = false,
	
	lighting = true,
	
	alphaTest = false,
	
	blendMode = "Opaque",
	
	textureAddressMode = "Wrap",
	
	glossiness = 100,
	
	depthBias = 0,

}

defineMaterial{
	name = "snail_shell_green_brown",
	
	diffuseMap = "mod_assets/textures/snail_green_brown_dif.tga",
	
	specularMap = "assets/textures/monsters/snail_spec.tga",
	
	normalMap = "assets/textures/monsters/snail_normal.tga",
	
	doubleSided = false,
	
	lighting = true,
	
	alphaTest = false,
	
	blendMode = "Opaque",
	
	textureAddressMode = "Wrap",
	
	glossiness = 40,
	
	depthBias = 0,

}

defineMaterial{
	
	name = "snail_rainbow",
	
	diffuseMap = "mod_assets/textures/snail_rainbow_dif.tga",
	
	specularMap = "assets/textures/monsters/snail_spec.tga",
	
	normalMap = "assets/textures/monsters/snail_normal.tga",
	
	doubleSided = false,
	
	lighting = true,
	
	alphaTest = false,
	
	blendMode = "Opaque",
	
	textureAddressMode = "Wrap",
	
	glossiness = 100,
	
	depthBias = 0,

}

defineMaterial{
	name = "snail_shell_rainbow",
	
	diffuseMap = "mod_assets/textures/snail_rainbow_dif.tga",
	
	specularMap = "assets/textures/monsters/snail_spec.tga",
	
	normalMap = "assets/textures/monsters/snail_normal.tga",
	
	doubleSided = false,
	
	lighting = true,
	
	alphaTest = false,
	
	blendMode = "Opaque",
	
	textureAddressMode = "Wrap",
	
	glossiness = 40,
	
	depthBias = 0,

}

defineMaterial{
	
	name = "snail_blue_green",
	
	diffuseMap = "mod_assets/textures/snail_blue_green_dif.tga",
	
	specularMap = "assets/textures/monsters/snail_spec.tga",
	
	normalMap = "assets/textures/monsters/snail_normal.tga",
	
	doubleSided = false,
	
	lighting = true,
	
	alphaTest = false,
	
	blendMode = "Opaque",
	
	textureAddressMode = "Wrap",
	
	glossiness = 100,
	
	depthBias = 0,

}

defineMaterial{
	name = "snail_shell_blue_green",
	
	diffuseMap = "mod_assets/textures/snail_blue_green_dif.tga",
	
	specularMap = "assets/textures/monsters/snail_spec.tga",
	
	normalMap = "assets/textures/monsters/snail_normal.tga",
	
	doubleSided = false,
	
	lighting = true,
	
	alphaTest = false,
	
	blendMode = "Opaque",
	
	textureAddressMode = "Wrap",
	
	glossiness = 40,
	
	depthBias = 0,

}





defineMaterial{

	name = "ogre_red_horn",
	diffuseMap = "mod_assets/textures/ogre_red_horn_dif.tga",
	specularMap = "assets/textures/monsters/ogre_spec.tga",
	normalMap = "assets/textures/monsters/ogre_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 20,
	depthBias = 0,
}


defineMaterial{
	
	name = "ogre_red_horn_hammer",
	
	diffuseMap = "mod_assets/textures/ogre_red_horn_hammer_dif.tga",
	
	specularMap = "assets/textures/monsters/ogre_hammer_spec.tga",
	
	normalMap = "assets/textures/monsters/ogre_hammer_normal.tga",
	
	doubleSided = false,
	
	lighting = true,
	
	alphaTest = false,
	
	blendMode = "Opaque",
	
	textureAddressMode = "Wrap",
	
	glossiness = 20,
	
	depthBias = 0,

}


defineMaterial{
	
	name = "shrakk_torr_bee",
	
	diffuseMap = "mod_assets/textures/shrakk_torr_bee_dif.tga",
	
	specularMap = "assets/textures/monsters/shrakk_torr_spec.tga",
	
	normalMap = "assets/textures/monsters/shrakk_torr_normal.tga",
	
	doubleSided = false,
	
	lighting = true,
	
	alphaTest = false,
	
	blendMode = "Opaque",
	
	textureAddressMode = "Wrap",
	
	glossiness = 45,
	
	depthBias = 0,

}

defineMaterial{
	name = "dark_wyvern",
	diffuseMap = "mod_assets/textures/dark_wyvern_dif.tga",
	specularMap = "assets/textures/monsters/wyvern_spec.tga",
	normalMap = "assets/textures/monsters/wyvern_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 65,
	depthBias = 0,
}

defineMaterial{
	name = "flame_wyvern",
	diffuseMap = "mod_assets/textures/flame_wyvern_dif.tga",
	specularMap = "assets/textures/monsters/wyvern_spec.tga",
	normalMap = "assets/textures/monsters/wyvern_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 65,
	depthBias = 0,
}

defineMaterial{
	name = "venom_wyvern",
	diffuseMap = "mod_assets/textures/venom_wyvern_dif.tga",
	specularMap = "assets/textures/monsters/wyvern_spec.tga",
	normalMap = "assets/textures/monsters/wyvern_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 65,
	depthBias = 0,
}

defineMaterial{
	name = "fire_lizard",
	diffuseMap = "mod_assets/textures/fire_lizard_dif.tga",
	specularMap = "assets/textures/monsters/ice_lizard_spec.tga",
	normalMap = "assets/textures/monsters/ice_lizard_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 65,
	depthBias = 0,
}

defineMaterial{
	name = "dark_lizard",
	diffuseMap = "mod_assets/textures/dark_lizard_dif.tga",
	specularMap = "assets/textures/monsters/ice_lizard_spec.tga",
	normalMap = "assets/textures/monsters/ice_lizard_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 65,
	depthBias = 0,
}

defineMaterial{
	
	name = "fire_lizard_steak",
	
	diffuseMap = "mod_assets/textures/fire_lizard_steak_dif.tga",
	
	specularMap = "assets/textures/items/ice_lizard_steak_spec.tga",
	
	doubleSided = false,
	
	lighting = true,
	
	alphaTest = false,
	
	blendMode = "Opaque",
	
	textureAddressMode = "Wrap",
	
	glossiness = 30,
	
	depthBias = 0,

}

defineMaterial{
	
	name = "dark_lizard_steak",
	
	diffuseMap = "mod_assets/textures/dark_lizard_steak_dif.tga",
	
	specularMap = "assets/textures/items/ice_lizard_steak_spec.tga",
	
	doubleSided = false,
	
	lighting = true,
	
	alphaTest = false,
	
	blendMode = "Opaque",
	
	textureAddressMode = "Wrap",
	
	glossiness = 30,
	
	depthBias = 0,

}

defineMaterial{
	name = "green_lizard",
	diffuseMap = "mod_assets/textures/green_lizard_dif.tga",
	specularMap = "assets/textures/monsters/ice_lizard_spec.tga",
	normalMap = "assets/textures/monsters/ice_lizard_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 65,
	depthBias = 0,
}

defineMaterial{
	
	name = "green_lizard_steak",
	
	diffuseMap = "mod_assets/textures/green_lizard_steak_dif.tga",
	
	specularMap = "assets/textures/items/ice_lizard_steak_spec.tga",
	
	doubleSided = false,
	
	lighting = true,
	
	alphaTest = false,
	
	blendMode = "Opaque",
	
	textureAddressMode = "Wrap",
	
	glossiness = 30,
	
	depthBias = 0,

}

defineMaterial{
	name = "herder_green",
	diffuseMap = "mod_assets/textures/herder_green_dif.tga",
	specularMap = "assets/textures/monsters/herder_spec.tga",
	normalMap = "assets/textures/monsters/herder_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = true,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 40,
	depthBias = 0,
}

defineMaterial{
	name = "herder_blue",
	diffuseMap = "mod_assets/textures/herder_blue_dif.tga",
	specularMap = "assets/textures/monsters/herder_spec.tga",
	normalMap = "assets/textures/monsters/herder_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = true,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 40,
	depthBias = 0,
}

defineMaterial{
	name = "crowern_purple",
	diffuseMap = "mod_assets/textures/crowern_purple_dif.tga",
	specularMap = "assets/textures/monsters/crowern_spec.tga",
	normalMap = "assets/textures/monsters/crowern_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = true,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 15,
	depthBias = 0,
}


defineMaterial{
	name = "crowern_red",
	diffuseMap = "mod_assets/textures/crowern_red_dif.tga",
	specularMap = "assets/textures/monsters/crowern_spec.tga",
	normalMap = "assets/textures/monsters/crowern_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = true,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 15,
	depthBias = 0,
}

defineMaterial{
	name = "scavenger_purple",
	diffuseMap = "mod_assets/textures/scavenger_purple_dif.tga",
	specularMap = "assets/textures/monsters/scavenger_spec.tga",
	normalMap = "assets/textures/monsters/scavenger_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 25,
	depthBias = 0,
}
defineMaterial{
	name = "skeleton_warrior_blue",
	diffuseMap = "mod_assets/textures/skeleton_warrior_blue_dif.tga",
	specularMap = "assets/textures/monsters/skeleton_warrior_spec.tga",
	normalMap = "assets/textures/monsters/skeleton_warrior_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 75,
	depthBias = 0,
}


defineMaterial{
	name = "skeleton_warrior_noxp",
	diffuseMap = "mod_assets/textures/skeleton_warrior_noxp_dif.tga",
	specularMap = "assets/textures/monsters/skeleton_warrior_spec.tga",
	normalMap = "assets/textures/monsters/skeleton_warrior_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 75,
	depthBias = 0,
}



defineMaterial{
	name = "spider_low",
	diffuseMap = "mod_assets/textures/spider_level2_dif.tga",
	specularMap = "assets/textures/monsters/spider_spec.tga",
	normalMap = "assets/textures/monsters/spider_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 40,
	depthBias = 0,
}


defineMaterial{
	name = "spider_medium",
	diffuseMap = "mod_assets/textures/spider_level3_dif.tga",
	specularMap = "assets/textures/monsters/spider_spec.tga",
	normalMap = "assets/textures/monsters/spider_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 40,
	depthBias = 0,
}


defineMaterial{
	name = "herder_noxp",
	diffuseMap = "mod_assets/textures/herder_small_noxp_dif.tga",
	specularMap = "assets/textures/monsters/herder_spec.tga",
	normalMap = "assets/textures/monsters/herder_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = true,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 40,
	depthBias = 0,
}



defineMaterial{
	name = "skeleton_warrior_shadow",
	diffuseMap = "mod_assets/textures/skeleton_warrior_shadow_dif.tga",
	specularMap = "assets/textures/monsters/skeleton_warrior_spec.tga",
	normalMap = "assets/textures/monsters/skeleton_warrior_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Additive",
	textureAddressMode = "Wrap",
	glossiness = 75,
	depthBias = 0,
}


defineMaterial{
	name = "skeleton_bow_shadow",
	diffuseMap = "mod_assets/textures/skeleton_warrior_bow_shadow_dif.tga",
	specularMap = "assets/textures/monsters/skeleton_warrior_bow_spec.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Additive",
	textureAddressMode = "Wrap",
	glossiness = 20,
	depthBias = 0,
}

defineMaterial{
	name = "skeleton_bow_noxp",
	diffuseMap = "mod_assets/textures/skeleton_warrior_bow_noxp_dif.tga",
	specularMap = "assets/textures/monsters/skeleton_warrior_bow_spec.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 20,
	depthBias = 0,
}

defineMaterial{
	name = "arrow_shadow",
	diffuseMap = "mod_assets/textures/arrow_shadow_dif.tga",
	specularMap = "assets/textures/items/arrow_spec.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Additive",
	textureAddressMode = "Wrap",
	glossiness = 20,
	depthBias = 0,
}

defineMaterial{
	name = "spider_web_rock",
	diffuseMap = "assets/textures/props/spider_webs_dif.tga",
	specularMap = "assets/textures/items/rock_spec.tga",
	doubleSided = true,
	lighting = false,
	alphaTest = false,
	blendMode = "Translucent",
	textureAddressMode = "Wrap",
	glossiness = 20,
	depthBias = 0,
}

defineMaterial{
	name = "egg_poison_rock",
	diffuseMap = "mod_assets/textures/scavenger_purple_dif.tga",
	specularMap = "assets/textures/items/rock_spec.tga",
	doubleSided = true,
	lighting = false,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 20,
	depthBias = 0,
}

defineMaterial{
	name = "snail_projectile_rock",
	diffuseMap = "mod_assets/textures/snail_red_purple_dif.tga",
	specularMap = "assets/textures/items/rock_spec.tga",
	doubleSided = true,
	lighting = false,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 20,
	depthBias = 0,
}

