-- This file has been generated by Dungeon Editor 1.3.7

-- TODO: place your custom dungeon object definitions here

defineObject{
   name = "eye_socket_left_fake",
   class = "Alcove",
   anchorPos = vec(0.21, 1.58, -0.45),
   targetPos = vec(0.2, 1.65, -0.45),
   targetSize = vec(0.1, 0.1, 0.1),
   placement = "wall",
   onInsertItem = function(self, item)
      return item.name == "blue_gem" and self:getItemCount() == 0
   end,
   onPickUpItem = function(self, item)
      if item.name == "blue_gem_fake" then
         return false
      else
         return true
      end
   end,
   editorIcon = 92,
}
defineObject{
   name = "eye_socket_right_fake",
   class = "Alcove",
   anchorPos = vec(-0.21, 1.58, -0.45),
   targetPos = vec(-0.2, 1.65, -0.45),
   targetSize = vec(0.1, 0.1, 0.1),
   placement = "wall",
   onInsertItem = function(self, item)
      return item.name == "blue_gem" and self:getItemCount() == 0
   end,
   onPickUpItem = function(self, item)
      if item.name == "blue_gem_fake" then
         return false
      else
         return true
      end
   end,
   editorIcon = 92,
}
defineObject{
   name = "eye_skull_left_fake",
   class = "Alcove",
   anchorPos = vec(0.22, 1.54, -0.46),
   targetPos = vec(0.21, 1.61, -0.46),
   targetSize = vec(0.1, 0.1, 0.1),
   placement = "wall",
   onInsertItem = function(self, item)
      return item.name == "stone_skull" and self:getItemCount() == 0
   end,
   onPickUpItem = function(self, item)
      if item.name == "skull_stone_fake" then
         return false
      else
         return true
      end
   end,
   editorIcon = 92,
}
defineObject{
   name = "eye_skull_right_fake",
   class = "Alcove",
   anchorPos = vec(-0.22, 1.54, -0.46),
   targetPos = vec(-0.21, 1.61, -0.46),
   targetSize = vec(0.1, 0.1, 0.1),
   placement = "wall",
   onInsertItem = function(self, item)
      return item.name == "stone_skull" and self:getItemCount() == 0
   end,
   onPickUpItem = function(self, item)
      if item.name == "skull_stone_fake" then
         return false
      else
         return true
      end
   end,
   editorIcon = 92,
}

defineObject{
	name = "mouth_socket_fake",
	class = "Alcove",
	anchorPos = vec(0, 1.1, -0.38),
	targetPos = vec(0, 1.1, -0.38),
	targetSize = vec(0.3, 0.3, 0.3),
	placement = "wall",
	onInsertItem = function(self, item)
		return item.name == "green_gem" and self:getItemCount() == 0
	end,
	   onPickUpItem = function(self, item)
      if item.name == "green_gem_fake" then
         return false
      else
         return true
      end
   end,
	editorIcon = 92,
}

defineObject{
	name = "round_gem_alcove_01_c_r_fake",
	class = "Alcove",
	model = "mod_assets/models/env/alcoves/round_gem_alcove_01_c_r.fbx",
	anchorPos = vec(0.5, 1.6, -0.075),
	anchorRotation = vec(45, 0, 0),
	targetPos = vec(0.5, 1.6, 0),
	targetSize = vec(0.05, 0.05, 0.05),
	onInsertItem = function(self, item)
		local allowed = {"itm_gem_black_01", "itm_gem_blue_01", "itm_gem_golden_orange_01", "itm_gem_green_01", "itm_gem_light_magenta_01", "itm_gem_magenta_01", "itm_gem_orange_01", "itm_gem_pastel_green_01", "itm_gem_pastel_yellow_01", "itm_gem_pure_cyan_01", "itm_gem_pure_green_01", "itm_gem_pure_green_cyan_01", "itm_gem_pure_magenta_01", "itm_gem_pure_violet_magenta_01", "itm_gem_pure_yellow_green_01", "itm_gem_red_01", "itm_gem_white_01", "itm_gem_yellow_01"}
		for i = 1, #allowed do
			if item.name == allowed[i] then
				return item.name == allowed[i] and self:getItemCount() == 0
			end
		end
	end,
	onPickUpItem = function(self, item)
		local fakegem = {"itm_gem_blue_01_fake","itm_gem_red_01_fake","itm_gem_yellow_01_fake","itm_gem_green_01_fake"}
		for i = 1, #fakegem do
			if item.name == fakegem[i] then
				return false
			else
				return true
			end
		end
	end,
	placement = "wall",
	replacesWall = false,
	editorIcon = 92,
}
defineObject{
	name = "round_gem_alcove_01_u_c_fake",
	class = "Alcove",
	model = "mod_assets/models/env/alcoves/round_gem_alcove_01_u_c.fbx",
	anchorPos = vec(0, 2.1, -0.075),
	anchorRotation = vec(45, 0, 0),
	targetPos = vec(0, 2.1, 0),
	targetSize = vec(0.05, 0.05, 0.05),
	onInsertItem = function(self, item)
		local allowed = {"itm_gem_black_01", "itm_gem_blue_01", "itm_gem_golden_orange_01", "itm_gem_green_01", "itm_gem_light_magenta_01", "itm_gem_magenta_01", "itm_gem_orange_01", "itm_gem_pastel_green_01", "itm_gem_pastel_yellow_01", "itm_gem_pure_cyan_01", "itm_gem_pure_green_01", "itm_gem_pure_green_cyan_01", "itm_gem_pure_magenta_01", "itm_gem_pure_violet_magenta_01", "itm_gem_pure_yellow_green_01", "itm_gem_red_01", "itm_gem_white_01", "itm_gem_yellow_01"}
		for i = 1, #allowed do
			if item.name == allowed[i] then
				return item.name == allowed[i] and self:getItemCount() == 0
			end
		end
	end,
	onPickUpItem = function(self, item)
		local fakegem = {"itm_gem_blue_01_fake","itm_gem_red_01_fake","itm_gem_yellow_01_fake","itm_gem_green_01_fake"}
		for i = 1, #fakegem do
			if item.name == fakegem[i] then
				return false
			else
				return true
			end
		end
	end,
	placement = "wall",
	replacesWall = false,
	editorIcon = 92,
}
defineObject{
	name = "round_gem_alcove_01_u_r_fake",
	class = "Alcove",
	model = "mod_assets/models/env/alcoves/round_gem_alcove_01_u_r.fbx",
	anchorPos = vec(0.5, 2.1, -0.075),
	anchorRotation = vec(45, 0, 0),
	targetPos = vec(0.5, 2.1, 0),
	targetSize = vec(0.05, 0.05, 0.05),
	onInsertItem = function(self, item)
		local allowed = {"itm_gem_black_01", "itm_gem_blue_01", "itm_gem_golden_orange_01", "itm_gem_green_01", "itm_gem_light_magenta_01", "itm_gem_magenta_01", "itm_gem_orange_01", "itm_gem_pastel_green_01", "itm_gem_pastel_yellow_01", "itm_gem_pure_cyan_01", "itm_gem_pure_green_01", "itm_gem_pure_green_cyan_01", "itm_gem_pure_magenta_01", "itm_gem_pure_violet_magenta_01", "itm_gem_pure_yellow_green_01", "itm_gem_red_01", "itm_gem_white_01", "itm_gem_yellow_01"}
		for i = 1, #allowed do
			if item.name == allowed[i] then
				return item.name == allowed[i] and self:getItemCount() == 0
			end
		end
	end,
	onPickUpItem = function(self, item)
		local fakegem = {"itm_gem_blue_01_fake","itm_gem_red_01_fake","itm_gem_yellow_01_fake","itm_gem_green_01_fake"}
		for i = 1, #fakegem do
			if item.name == fakegem[i] then
				return false
			else
				return true
			end
		end
	end,
	placement = "wall",
	replacesWall = false,
	editorIcon = 92,
}

defineObject{
	name = "round_gem_alcove_01_l_l_fake",
	class = "Alcove",
	model = "mod_assets/models/env/alcoves/round_gem_alcove_01_l_l.fbx",
	anchorPos = vec(-0.5, 1.1, -0.075),
	anchorRotation = vec(45, 0, 0),
	targetPos = vec(-0.5, 1.1, 0),
	targetSize = vec(0.05, 0.05, 0.05),
	onInsertItem = function(self, item)
		local allowed = {"itm_gem_black_01", "itm_gem_blue_01", "itm_gem_golden_orange_01", "itm_gem_green_01", "itm_gem_light_magenta_01", "itm_gem_magenta_01", "itm_gem_orange_01", "itm_gem_pastel_green_01", "itm_gem_pastel_yellow_01", "itm_gem_pure_cyan_01", "itm_gem_pure_green_01", "itm_gem_pure_green_cyan_01", "itm_gem_pure_magenta_01", "itm_gem_pure_violet_magenta_01", "itm_gem_pure_yellow_green_01", "itm_gem_red_01", "itm_gem_white_01", "itm_gem_yellow_01"}
		for i = 1, #allowed do
			if item.name == allowed[i] then
				return item.name == allowed[i] and self:getItemCount() == 0
			end
		end
	end,
	onPickUpItem = function(self, item)
		local fakegem = {"itm_gem_blue_01_fake","itm_gem_red_01_fake","itm_gem_yellow_01_fake","itm_gem_green_01_fake"}
		for i = 1, #fakegem do
			if item.name == fakegem[i] then
				return false
			else
				return true
			end
		end
	end,
	placement = "wall",
	replacesWall = false,
	editorIcon = 92,
}
defineObject{
	name = "square_gem_alcove_01_c_c_fake",
	class = "Alcove",
	model = "mod_assets/models/env/alcoves/square_gem_alcove_01_c_c.fbx",
	anchorPos = vec(0, 1.6, -0.07),
	anchorRotation = vec(45, 0, 0),
	targetPos = vec(0, 1.6, 0),
	targetSize = vec(0.05, 0.05, 0.05),
	onInsertItem = function(self, item)
		local allowed = {"itm_gem_black_01", "itm_gem_blue_01", "itm_gem_golden_orange_01", "itm_gem_green_01", "itm_gem_light_magenta_01", "itm_gem_magenta_01", "itm_gem_orange_01", "itm_gem_pastel_green_01", "itm_gem_pastel_yellow_01", "itm_gem_pure_cyan_01", "itm_gem_pure_green_01", "itm_gem_pure_green_cyan_01", "itm_gem_pure_magenta_01", "itm_gem_pure_violet_magenta_01", "itm_gem_pure_yellow_green_01", "itm_gem_red_01", "itm_gem_white_01", "itm_gem_yellow_01"}
		for i = 1, #allowed do
			if item.name == allowed[i] then
				return item.name == allowed[i] and self:getItemCount() == 0
			end
		end
	end,
	onPickUpItem = function(self, item)
			if item.name == "itm_gem_white_01_fake" then
				return false
			else
				return true
			end
		
	end,
	placement = "wall",
	replacesWall = false,
	editorIcon = 92,
}

defineObject{
	name = "square_gem_alcove_02_c_l_fake",
	class = "Alcove",
	model = "mod_assets/models/env/alcoves/square_gem_alcove_02_c_l.fbx",
	anchorPos = vec(-0.5, 1.6, -0.085),
	anchorRotation = vec(45, 0, 90),
	targetPos = vec(-0.5, 1.6, 0),
	targetSize = vec(0.05, 0.05, 0.05),
	onInsertItem = function(self, item)
		local allowed = {"itm_gem_black_02", "itm_gem_blue_02", "itm_gem_golden_orange_02", "itm_gem_green_02", "itm_gem_light_magenta_02", "itm_gem_magenta_02", "itm_gem_orange_02", "itm_gem_pastel_green_02", "itm_gem_pastel_yellow_02", "itm_gem_pure_cyan_02", "itm_gem_pure_green_02", "itm_gem_pure_green_cyan_02", "itm_gem_pure_magenta_02", "itm_gem_pure_violet_magenta_02", "itm_gem_pure_yellow_green_02", "itm_gem_red_02", "itm_gem_white_02", "itm_gem_yellow_02"}
		for i = 1, #allowed do
			if item.name == allowed[i] then
				return item.name == allowed[i] and self:getItemCount() == 0
			end
		end
	end,
		onPickUpItem = function(self, item)
			if item.name == "itm_gem_white_02_fake" then
				return false
			else
				return true
			end
		
	end,
	placement = "wall",
	replacesWall = false,
	editorIcon = 92,
}
defineObject{
	name = "square_gem_alcove_06_c_r_fake",
	class = "Alcove",
	model = "mod_assets/models/env/alcoves/square_gem_alcove_06_c_r.fbx",
	anchorPos = vec(0.5, 1.6, -0.08),
	anchorRotation = vec(45, 0, 90),
	targetPos = vec(0.5, 1.6, 0),
	targetSize = vec(0.05, 0.05, 0.05),
	onInsertItem = function(self, item)
		local allowed = {"itm_gem_black_06", "itm_gem_blue_06", "itm_gem_golden_orange_06", "itm_gem_green_06", "itm_gem_light_magenta_06", "itm_gem_magenta_06", "itm_gem_orange_06", "itm_gem_pastel_green_06", "itm_gem_pastel_yellow_06", "itm_gem_pure_cyan_06", "itm_gem_pure_green_06", "itm_gem_pure_green_cyan_06", "itm_gem_pure_magenta_06", "itm_gem_pure_violet_magenta_06", "itm_gem_pure_yellow_green_06", "itm_gem_red_06", "itm_gem_white_06", "itm_gem_yellow_06"}
		for i = 1, #allowed do
			if item.name == allowed[i] then
				return item.name == allowed[i] and self:getItemCount() == 0
			end
		end
	end,
	onPickUpItem = function(self, item)
			if item.name == "itm_gem_white_06_fake" then
				return false
			else
				return true
			end
		
	end,
	placement = "wall",
	replacesWall = false,
	editorIcon = 92,
}
defineObject{
	name = "dungeon_pillar_center",
	class = "Blockage",
	model = "assets/models/env/dungeon_pillar.fbx",
	placement = "floor",
	repelProjectiles = true,
	hitSound = "impact_blade",
	editorIcon = 100,
}

defineObject{
	name = "prison_pillar_center",
	class = "Blockage",
	model = "assets/models/env/prison_pillar.fbx",
	placement = "floor",
	repelProjectiles = true,
	hitSound = "impact_blade",
	editorIcon = 100,
}
defineObject{
	name = "temple_pillar_center",
	class = "Blockage",
	model = "mod_assets/models/decorations/temple_middle_pillar.fbx",
	placement = "floor",
	repelProjectiles = true,
	hitSound = "impact_blade",
	editorIcon = 100,
}
defineObject{
  	  name = "skeleton_floor",
   	 class = "Decoration",
   	 model = "mod_assets/models/decorations/floor_skeleton.fbx",
	replaceFloor= false,
    	placement = "floor",
	editorIcon = 100,
}

defineObject{
	name = "splotchy_dungeon-wall",
	class = "Decoration",
	model = "mod_assets/models/decorations/splotchy_dungeon_wall.fbx",
	placement = "wall",
	replacesWall = true,
	editorIcon = 92,
}
defineObject{
	name = "mosswall_symbol8",
	class = "Decoration",
	model = "mod_assets/models/decorations/moss_wall_symbol8.fbx",
	placement = "wall",
	replacesWall = true,
	editorIcon = 92,
}
defineObject{
	name = "mosswall_symbol7",
	class = "Decoration",
	model = "mod_assets/models/decorations/moss_wall_symbol7.fbx",
	placement = "wall",
	replacesWall = true,
	editorIcon = 92,
}
defineObject{
	name = "mosswall_symbol6",
	class = "Decoration",
	model = "mod_assets/models/decorations/moss_wall_symbol6.fbx",
	placement = "wall",
	replacesWall = true,
	editorIcon = 92,
}
defineObject{
	name = "mosswall_symbol5",
	class = "Decoration",
	model = "mod_assets/models/decorations/moss_wall_symbol5.fbx",
	placement = "wall",
	replacesWall = true,
	editorIcon = 92,
}
defineObject{
	name = "mosswall_symbol4",
	class = "Decoration",
	model = "mod_assets/models/decorations/moss_wall_symbol4.fbx",
	placement = "wall",
	replacesWall = true,
	editorIcon = 92,
}
defineObject{
	name = "mosswall_symbol3",
	class = "Decoration",
	model = "mod_assets/models/decorations/moss_wall_symbol3.fbx",
	placement = "wall",
	replacesWall = true,
	editorIcon = 92,
}
defineObject{
	name = "mosswall_symbol2",
	class = "Decoration",
	model = "mod_assets/models/decorations/moss_wall_symbol2.fbx",
	placement = "wall",
	replacesWall = true,
	editorIcon = 92,
}
defineObject{
	name = "mosswall_symbol1",
	class = "Decoration",
	model = "mod_assets/models/decorations/moss_wall_symbol1.fbx",
	placement = "wall",
	replacesWall = true,
	editorIcon = 92,
}

defineObject{
	name = "dragon_eggs",
	class = "Blockage",
	model = "mod_assets/models/decorations/dragon_eggs.fbx",
	brokenModel = "mod_assets/models/decorations/dragon_eggs_broken.fbx",
	placement = "floor",
	health = 30,
	evasion = -1000,
	hitSound = "spider_eggs_hit",
	hitEffect = "hit_goo",
	editorIcon = 56,
}
defineObject{
	name = "goromorg_statue_blockage",
   	 class = "Blockage",
	model = "mod_assets/models/decorations/goromorg_statue_blockage.fbx",
	placement = "floor",
	repelProjectiles = true,
	hitSound = "impact_blade",
	editorIcon = 56,
}
defineObject{
	name = "boulder_blockage",
   	 class = "Blockage",
	model = "mod_assets/models/decorations/boulder.fbx",
	placement = "floor",
	repelProjectiles = true,
	hitSound = "impact_blade",
	editorIcon = 56,
}
defineObject{
	name = "wall_shelf",
	class = "Alcove",
	anchorPos = vec(0, 1.0, -0.2),
	targetPos = vec(0, 1.0, -0.2),
	targetSize = vec(0.3, 0.3, 0.3),
	model = "mod_assets/models/decorations/wall_fountain.fbx",
	placement = "wall",
	replacesWall = false,
	editorIcon = 92,
}
defineObject{
	name = "temple_wall_grate",
	class = "Decoration",
	model = "mod_assets/models/decorations/wall_grate.fbx",
	placement = "wall",
	replacesWall = true,
	editorIcon = 92,
}
defineObject{
	name = "temple_receptor",
	class = "Receptor",
	model = "mod_assets/models/decorations/temple_receptor.fbx",
	placement = "wall",
	editorIcon = 72,
}
defineObject{
	name = "gobelin_tricorne",
	class = "WallTapestry",
	model = "mod_assets/models/gobelin/gobelin_tricorne.fbx",
	brokenModel = "mod_assets/models/gobelin/gobelin_tricorne_torn.fbx",
	placement = "wall",
	editorIcon = 92,
}

defineObject{
	name = "gobelin_wolfcircle",
	class = "WallTapestry",
	model = "mod_assets/models/gobelin/gobelin_wolfcircle.fbx",
	brokenModel = "mod_assets/models/gobelin/gobelin_wolfcircle_torn.fbx",
	placement = "wall",
	editorIcon = 92,
}

defineObject{
	name = "gobelin_sacrifice",
	class = "WallTapestry",
	model = "mod_assets/models/gobelin/gobelin_sacrifice.fbx",
	brokenModel = "mod_assets/models/gobelin/gobelin_sacrifice_torn.fbx",
	placement = "wall",
	editorIcon = 92,
}

defineObject{
	name = "gobelin_wheel",
	class = "WallTapestry",
	model = "mod_assets/models/gobelin/gobelin_wheel.fbx",
	brokenModel = "mod_assets/models/gobelin/gobelin_wheel_torn.fbx",
	placement = "wall",
	editorIcon = 92,
}

defineObject{
	name = "boulder",
	class = "Item",
	uiName = "Boulder",
	gfxIndex = 0,
	model = "mod_assets/models/boulder.fbx",
	attackSound = "null",
	impactSound = "boulder_hit",
	projectileRotationSpeed = 3,
	projectileRotationX = 90,
	projectileRotationY = -90,
	weight = 1000,
}

defineObject{
	name = "ast_dwarf_lamp",
	class = "TorchHolder",  
	model = "mod_assets/models/ast_dwarf_lamp.fbx",
	anchorPos = vec(0.05, 1.53, 2),
	anchorRotation = vec(0, -20, -90),
	placement = "wall",
	editorIcon = 84,
}

defineObject{
	name = "ast_dwarf_gobelin",
	class = "WallTapestry",
	model = "mod_assets/models/ast_dwarf_gobelin.fbx",
	brokenModel = "mod_assets/models/ast_dwarf_gobelin_torn.fbx",
	placement = "wall",
	editorIcon = 92,
}

defineObject{
	name = "ast_dwarf_catacomb_skeleton_up",
	class = "Decoration",
	model = "mod_assets/models/ast_dwarf_catacomb_skeleton_up.fbx",
	placement = "wall",
	replacesWall = true,
	editorIcon = 92,
}

defineObject{
	name = "ast_dwarf_catacomb_skeleton_down",
	class = "Decoration",
	model = "mod_assets/models/ast_dwarf_catacomb_skeleton_down.fbx",
	placement = "wall",
	replacesWall = true,
	editorIcon = 92,
}

defineObject{
	name = "ast_dwarf_altar",
	class = "Altar",
	model = "mod_assets/models/ast_dwarf_altar.fbx",
	placement = "floor",
	editorIcon = 52,
}

defineObject{
	name = "ast_dwarf_hammer_altar",
	class = "Altar",
	model = "mod_assets/models/ast_dwarf_hammer_altar.fbx",
	placement = "floor",
	editorIcon = 52,
}

defineObject{
	name = "ast_dwarf_cracked_altar",
	class = "Altar",
	model = "mod_assets/models/ast_dwarf_cracked_altar.fbx",
	placement = "floor",
	editorIcon = 52,
}

defineObject{
    name = "ast_dwarf_hammer_wall",
    class = "Decoration",
    model = "mod_assets/models/ast_dwarf_hammer_wall.fbx",
    placement = "wall",
    replacesWall = true,
	editorIcon = 92,
}

defineObject{
	name = "ast_dwarf_hammer_statue",
	class = "Blockage",
	model = "mod_assets/models/ast_dwarf_hammer_statue.fbx",
        brokenModel = "assets/models/env/barrel_crate_block_broken.fbx",
	placement = "floor",
	editorIcon = 100,
	hitSound = "impact_blade",
}

defineObject{
    name = "ast_dwarf_hammer_statue_wall",
    class = "Decoration",
    model = "mod_assets/models/ast_dwarf_hammer_statue_wall.fbx",
    placement = "wall",
    replacesWall = true,
	editorIcon = 92,
}



defineObject{
    name = "skull_pile",
    class = "Decoration",
    model = "mod_assets/models/impaledskullpile.fbx",
    placement = "floor",
	editorIcon = 100,
}


defineObject{
   name = "illusion_dungeon",
   class = "TorchHolder",
   model = "assets/models/env/dungeon_secret_door.fbx",
   anchorPos = vec(0.05, 1.53, -0.25),
   anchorRotation = vec(0, -20, -90),
   placement = "wall",
   editorIcon = 84,
}

defineObject{
   name = "illusion_temple",
   class = "TorchHolder",
   model = "assets/models/env/temple_secret_door.fbx",
   anchorPos = vec(0.05, 1.53, -0.25),
   anchorRotation = vec(0, -20, -90),
   placement = "wall",
   editorIcon = 84,
}

defineObject{
   name = "illusion_prison",
   class = "TorchHolder",
   model = "assets/models/env/prison_secret_door.fbx",
   anchorPos = vec(0.05, 1.53, -0.25),
   anchorRotation = vec(0, -20, -90),
   placement = "wall",
   editorIcon = 84,
}

defineObject{
   name = "illusion_clean_dungeon",
   class = "TorchHolder",
   model = "mod_assets/models/cleanwall/clean_dungeon_secret_door.fbx",
   anchorPos = vec(0.05, 1.53, -0.25),
   anchorRotation = vec(0, -20, -90),
   placement = "wall",
   editorIcon = 84,
}


cloneObject{
	name = "invisible_wall",
	baseObject = "dungeon_secret_door",
	model = "mod_assets/models/invisible_wall.fbx",

}

cloneObject{
	name = "dungeon_secret_catacomb",
	baseObject = "dungeon_secret_door",
	model = "mod_assets/models/dungeon_secret_catacomb.fbx",

}
cloneObject{
	name = "dungeon_secret_catacomb_down",
	baseObject = "dungeon_secret_door",
	model = "mod_assets/models/dungeon_secret_catacomb_down.fbx",

}
cloneObject{
	name = "dungeon_secret_catacomb_up",
	baseObject = "dungeon_secret_door",
	model = "mod_assets/models/dungeon_secret_catacomb_up.fbx",

}

defineObject{
   name = "dummy_floor_dungeon",
   class = "Decoration",
   model = "assets/models/env/dungeon_floor_01.fbx",
   placement = "floor",
   replacesFloor = true,
   editorIcon = 136,
}

defineObject{
   name = "clean_dummy_floor_dungeon",
   class = "Decoration",
   model = "mod_assets/models/cleanwall/dungeon_floor_clean_01.fbx",
   placement = "floor",
   replacesFloor = true,
   editorIcon = 136,
}

defineObject{
	name = "practice_dummy",
	class = "Blockage",
	model = "mod_assets/models/practice_dummy.fbx",
	placement = "floor",
	replacesWall = true,
	repelProjectiles = true,
	hitSound = "impact_blade",
	editorIcon = 96,
}

cloneObject{
   name = "illusionwallBlocker",
   baseObject = "torch_holder",
    model = "assets/models/env/dungeon_wall_01.fbx",
    onInsertItem = function()
        return false
    end,
    editorIcon = 120,
}

cloneObject{
   name = "illusionwalltwowayBlocker",
   baseObject = "torch_holder",
    model = "assets/models/env/dungeon_wall_01.fbx",
    onInsertItem = function()
        return false
    end,
    editorIcon = 120,
}
cloneObject{
   name = "illusioncatacombclearBlocker",
   baseObject = "torch_holder",
   model = "assets/models/env/dungeon_catacomb_empty.fbx",
    onInsertItem = function()
        return false
    end,
    editorIcon = 120,
}


cloneObject{
   name = "illusioncatacombdownBlocker",
   baseObject = "torch_holder",
   model = "assets/models/env/dungeon_catacomb_skeleton_down.fbx",
    onInsertItem = function()
        return false
    end,
    editorIcon = 120,
}


cloneObject{
   name = "illusioncatacombupBlocker",
   baseObject = "torch_holder",
   model = "assets/models/env/dungeon_catacomb_skeleton_up.fbx",
    onInsertItem = function()
        return false
    end,
    editorIcon = 120,
}
defineObject{
	name = "anti_click",
	class = "WallTapestry",
	model = "mod_assets/models/anti_click.fbx",
	brokenModel = "mod_assets/models/anti_click.fbx",
	placement = "wall",
	editorIcon = 92,
}

--dragon socket
defineObject{
name = "dragon_socket",
class = "Alcove",
anchorPos = vec(0.0, 1.49, 0.65),
targetPos = vec(0.0, 1.35, 0.35),
targetSize = vec(0.3, 0.3, 0.3),
placement = "wall",
onInsertItem = function(self, item)
return (item.name == "magic_orb" or item.name == "zhandul_orb" or

item.name == "machine_part_north") and self:getItemCount() == 0
end,
editorIcon = 92,
}

defineObject{
name = "dragon_socket_gem",
class = "Alcove",
anchorPos = vec(0.0, 1.49, 0.65),
targetPos = vec(0.0, 1.35, 0.35),
targetSize = vec(0.3, 0.3, 0.3),
placement = "wall",
onInsertItem = function(self, item)
return (item.name == "green_gem" or item.name == "red_gem" or

item.name == "blue_gem") and self:getItemCount() == 0
end,
editorIcon = 92,
}

defineObject{
name = "dragon_socket_flame_left",
class = "LightSource",
lightPosition = vec(0.15, 1.85, 1.33),
lightRange = 12,
lightColor = vec(0.7, 0.5, 0.5),
brightness = 10,
castShadow = true,
particleSystem = "torch", -- u can find other particle systems at http://www.grimrock.net/modding/list-of ... e-systems/
placement = "floor",
editorIcon = 88,
}

defineObject{
name = "dragon_socket_flame_right",
class = "LightSource",
lightPosition = vec(-0.15, 1.85, 1.33),
lightRange = 12,
lightColor = vec(0.7, 0.5, 0.5),
brightness = 10,
castShadow = true,
particleSystem = "torch",
placement = "floor",
editorIcon = 88,
}


defineObject{
	name = "boulder_blockage_hit",
   	 class = "Blockage",
	model = "mod_assets/models/decorations/boulder.fbx",
	brokenModel = "mod_assets/models/deep_dungeon/deep_dungeon_floor_dirt.fbx",
	placement = "floor",
	health = 60,
	evasion = -1000,
	repelProjectiles = true,
	hitSound = "impact_blade",
	hitEffect = "hit_wood",
	editorIcon = 56,
	onDie = function(self, dir)
      counter_boulder_hit:setValue(0)
   end,
}







