-- This file has been generated by Dungeon Editor 1.3.7
defineSound{
   name = "earthquake_8s",
   filename = "mod_assets/sounds/earthquake_8s.wav",
   loop = false,
   volume = 1,
   minDistance = 1,
   maxDistance = 6,
}

defineSound{
   name = "earthquake_11s",
   filename = "mod_assets/sounds/earthquake_11s.wav",
   loop = false,
   volume = 1,
   minDistance = 1,
   maxDistance = 6,
}

defineSound{
   name = "earthquake_stop",
   filename = "assets/samples/env/earthquake_01.wav",
   loop = false,
   volume = 1,
   minDistance = 1,
   maxDistance = 6,
}

defineSound{
name = "wall_lantern_crackling",
filename = "assets/samples/env/torch_burning_01.wav",
loop = true,
volume = 0.5,
minDistance = 2,
maxDistance = 6,
}


defineSound{
       name = "ghost_alert",  
       filename = "mod_assets/sounds/ghost_alert_01.wav",
       loop = false,
       volume = 1,
       minDistance = 2,
       maxDistance = 6,
}
defineSound{
       name = "ghost_alert2",  
       filename = "mod_assets/sounds/ghost_alert_02.wav",
       loop = false,
       volume = 1,
       minDistance = 2,
       maxDistance = 6,
}
defineSound{
       name = "ghost_generic",  
       filename = "mod_assets/sounds/generic_moan_01.wav",
       loop = false,
       volume = 1,
       minDistance = 2,
       maxDistance = 6,
}

defineSound{
       name = "ghost_close",  
       filename = "mod_assets/sounds/ghost_alert_06.wav",
       loop = false,
       volume = 1,
       minDistance = 2,
       maxDistance = 6,
}
defineSound{
       name = "intrigue",  
       filename = "mod_assets/sounds/magic_hit_09.wav",
       loop = false,
       volume = 1,
       minDistance = 2,
       maxDistance = 6,
}

defineSound{
       name = "rugissement",  
       filename = "mod_assets/sounds/monster_alert_predator_01.wav",
       loop = false,
       volume = 1,
       minDistance = 2,
       maxDistance = 6,
}

defineSound{
       name = "door",  
       filename = "mod_assets/sounds/MouthDoorSound.wav",
       loop = false,
       volume = 1,
       minDistance = 2,
       maxDistance = 6,
}

defineSound{
       name = "evil_laugh_1",  
       filename = "mod_assets/sounds/kira1.wav",
       loop = false,
       volume = 1,
       minDistance = 2,
       maxDistance = 6,
}
defineSound{
       name = "evil_laugh_2",  
       filename = "mod_assets/sounds/kira2.wav",
       loop = false,
       volume = 1,
       minDistance = 2,
       maxDistance = 6,
}
defineSound{
       name = "evil_laugh_3",  
       filename = "mod_assets/sounds/kira3.wav",
       loop = false,
       volume = 1,
       minDistance = 2,
       maxDistance = 6,
}
defineSound{
       name = "evil_laugh_4",  
       filename = "mod_assets/sounds/kira4.wav",
       loop = false,
       volume = 1,
       minDistance = 2,
       maxDistance = 6,
}
defineSound{
       name = "evil_laugh_5",  
       filename = "mod_assets/sounds/kira5.wav",
       loop = false,
       volume = 1,
       minDistance = 2,
       maxDistance = 6,
}
defineSound{
       name = "evil_laugh_6",  
       filename = "mod_assets/sounds/kira6.wav",
       loop = false,
       volume = 1,
       minDistance = 2,
       maxDistance = 6,
}
defineSound{
       name = "evil_laugh_7",  
       filename = "mod_assets/sounds/kira7.wav",
       loop = false,
       volume = 1,
       minDistance = 2,
       maxDistance = 6,
}
defineSound{
       name = "evil_laugh_8",  
       filename = "mod_assets/sounds/kira8.wav",
       loop = false,
       volume = 1,
       minDistance = 2,
       maxDistance = 6,
}
defineSound{
       name = "evil_laugh_9",  
       filename = "mod_assets/sounds/kira9.wav",
       loop = false,
       volume = 1,
       minDistance = 2,
       maxDistance = 6,
}
defineSound{
       name = "evil_laugh_10",  
       filename = "mod_assets/sounds/kira10.wav",
       loop = false,
       volume = 1,
       minDistance = 2,
       maxDistance = 6,
}

defineSound{
       name = "musique1",  
       filename = "mod_assets/sounds/musique1.wav",
       loop = false,
       volume = 1,
       minDistance = 2,
       maxDistance = 6,
}

defineSound{
       name = "haunt1",  
       filename = "mod_assets/sounds/SoCHaunted02.wav",
       loop = false,
       volume = 1,
       minDistance = 2,
       maxDistance = 6,
}

defineSound{
       name = "ghost_effet",  
       filename = "mod_assets/sounds/SoCWraith01.wav",
       loop = false,
       volume = 1,
       minDistance = 2,
       maxDistance = 6,
}

defineSound{
       name = "ghost_cri",  
       filename = "mod_assets/sounds/ghost_vanquish_02.wav",
       loop = false,
       volume = 1,
       minDistance = 2,
       maxDistance = 6,
}


defineSound{
name = "boulder_rolling",
filename = "mod_assets/sounds/boulder_rolling.wav",
loop = false,
volume = 1.0,
minDistance = 1,
maxDistance = 10,
}
defineSound{
name = "boulder_hit",
filename = "mod_assets/sounds/boulder_hit.wav",
loop = false,
volume = 2.0,
minDistance = 1,
maxDistance = 20,
}

defineSound{
       name = "ghost_effet2",  
       filename = "mod_assets/sounds/SoCWraith03.wav",
       loop = false,
       volume = 1,
       minDistance = 2,
       maxDistance = 6,
}

defineSound{
       name = "effet_magique1",  
       filename = "mod_assets/sounds/SoCWraith11.wav",
       loop = false,
       volume = 1,
       minDistance = 2,
       maxDistance = 6,
}

defineSound{
       name = "ghost_effet3",  
       filename = "mod_assets/sounds/SoCWraith10.wav",
       loop = false,
       volume = 1,
       minDistance = 2,
       maxDistance = 6,
}

defineSound{
       name = "tech_sourd",  
       filename = "mod_assets/sounds/tech_whir_03.wav",
       loop = true,
       volume = 1,
       minDistance = 2,
       maxDistance = 6,
}

defineSound{
       name = "tech_sourd2",  
       filename = "mod_assets/sounds/tech_whir_06.wav",
       loop = false,
       volume = 1,
       minDistance = 2,
       maxDistance = 6,
}


defineSound{
       name = "magic_intrigue",  
       filename = "mod_assets/sounds/magic_wand_01.wav",
       loop = false,
       volume = 1,
       minDistance = 2,
       maxDistance = 6,
}

defineSound{
       name = "magic_intrigue2",  
       filename = "mod_assets/sounds/magic_wand_01bis.wav",
       loop = false,
       volume = 1,
       minDistance = 2,
       maxDistance = 6,
}


defineSound{
       name = "ghost_son",  
       filename = "mod_assets/sounds/SoCWraith02.wav",
       loop = false,
       volume = 1,
       minDistance = 2,
       maxDistance = 6,
}

defineSound{
       name = "dragon_distant1",  
       filename = "mod_assets/sounds/npc_dragon_flightroar_distant_b_01.wav",
       loop = false,
       volume = 1,
       minDistance = 2,
       maxDistance = 6,
}
defineSound{
       name = "dragon_distant2",  
       filename = "mod_assets/sounds/npc_dragon_flightroar_distant_b_02.wav",
       loop = false,
       volume = 1,
       minDistance = 2,
       maxDistance = 6,
}
defineSound{
       name = "dragon_distant3",  
       filename = "mod_assets/sounds/npc_dragon_flightroar_distant_b_03.wav",
       loop = false,
       volume = 1,
       minDistance = 2,
       maxDistance = 6,
}
defineSound{
       name = "dragon_distant4",  
       filename = "mod_assets/sounds/npc_dragon_flightroar_distant_b_04.wav",
       loop = false,
       volume = 1,
       minDistance = 2,
       maxDistance = 6,
}
defineSound{
       name = "dragon_distant5",  
       filename = "mod_assets/sounds/npc_dragon_flightroar_distant_b_05.wav",
       loop = false,
       volume = 1,
       minDistance = 2,
       maxDistance = 6,
}
defineSound{
       name = "dragon_distant6",  
       filename = "mod_assets/sounds/npc_dragon_flightroar_distant_b_06.wav",
       loop = false,
       volume = 1,
       minDistance = 2,
       maxDistance = 6,
}
defineSound{
       name = "dragon_distant7",  
       filename = "mod_assets/sounds/npc_dragon_flightroar_distant_b_07.wav",
       loop = false,
       volume = 1,
       minDistance = 2,
       maxDistance = 6,
}
defineSound{
       name = "dragon_distant8",  
       filename = "mod_assets/sounds/npc_dragon_flightroar_distant_b_08.wav",
       loop = false,
       volume = 1,
       minDistance = 2,
       maxDistance = 6,
}

defineSound{
       name = "dragon_distant9",  
       filename = "mod_assets/sounds/npc_dragon_flightroar_distant_01.wav",
       loop = false,
       volume = 1,
       minDistance = 2,
       maxDistance = 6,
}

defineSound{
       name = "dragon_distant10",  
       filename = "mod_assets/sounds/npc_dragon_flightroar_distant_02.wav",
       loop = false,
       volume = 1,
       minDistance = 2,
       maxDistance = 6,
}

defineSound{
       name = "dragon_distant11",  
       filename = "mod_assets/sounds/npc_dragon_flightroarobstructed_01.wav",
       loop = false,
       volume = 1,
       minDistance = 2,
       maxDistance = 6,
}

defineSound{
       name = "dragon_distant12",  
       filename = "mod_assets/sounds/npc_dragon_flightroarobstructed_02.wav",
       loop = false,
       volume = 1,
       minDistance = 2,
       maxDistance = 6,
}

defineSound{
       name = "dragon_distant13",  
       filename = "mod_assets/sounds/npc_dragon_flightroarobstructed_03.wav",
       loop = false,
       volume = 1,
       minDistance = 2,
       maxDistance = 6,
}

